export type {
    EmailPlaceholder,
    EmailAudience,
    EmailComposeDraft,
    EmailComposeResult,
    EmailConfig,
    EmailConfigDraft,
    EmailFilters,
    EmailMessage,
    EmailProvider,
    EmailRecipientMode,
    EmailRecipientOption,
    EmailStats,
    EmailStatus,
    EmailTemplate,
    EmailTemplateDraft,
    EmailTrigger,
    EmailTriggerDraft,
} from '@webgame-cloud/api/contracts'
export {
    EMAIL_AUDIENCES,
    EMAIL_PROVIDERS,
    EMAIL_PLACEHOLDERS,
    EMAIL_RECIPIENT_MODES,
    EMAIL_STATUSES,
} from '@webgame-cloud/api/contracts'
