import { ApiErrorCode, RESOURCE_LABELS } from '@appkit/api/contracts'

const ERROR_MESSAGES = {
    unauthorized: 'Sign in to continue.',
    forbidden: 'You do not have permission to do that.',
    not_found: 'That could not be found.',
    conflict: 'That change conflicts with the current state — refresh and try again.',
    invalid_input: 'Some of the entered values are invalid.',
    unavailable: 'The service is temporarily unavailable. Try again shortly.',
    request_failed: 'The request failed. Please try again.',
    internal_error: 'Something went wrong on our side. Please try again.',
    cross_origin_rejected: 'The request was blocked for security reasons.',
    invalid_body: (field = 'a field') => `Invalid value for “${field}”.`,
    user_not_found: (id = '') => (id ? `Account “${id}” could not be found.` : 'That account could not be found.'),
    name_required: 'A name is required.',
    email_exists: 'A user with that email already exists.',
    account_deactivated: 'This account is deactivated.',
    owner_cannot_self_delete: 'The owner account cannot delete itself — hand the owner role over first.',
    self_impersonation: 'You are already signed in as this account.',
    self_role_change: 'You cannot change your own role or deactivate yourself.',
    self_access_change: 'You cannot change your own permissions or limits.',
    last_owner: 'The last owner cannot be demoted or deactivated.',
    sso_not_configured: 'This sign-in provider is not configured on this server.',
    dev_login_disabled: 'Developer login is disabled.',
    identity_not_found: 'That sign-in method is not connected to your account.',
    identity_linked_elsewhere: 'That account is already connected to a different user.',
    last_identity: 'You cannot disconnect your only sign-in method.',
    session_not_found: 'That session has already ended.',
    current_session: 'This is the device you are using — sign out from the menu instead.',
    target_not_found: 'The reported content could not be found.',
    report_exists: 'You already have an open report for this.',
    report_not_found: 'That report could not be found.',
    report_not_pending: 'This report has already been resolved.',
    invalid_push_endpoint: 'That push subscription is invalid.',
    id_required: 'A valid identifier is required.',
    role_not_found: (id = '') => (id ? `Role “${id}” could not be found.` : 'That role could not be found.'),
    role_exists: 'A role with that identifier already exists.',
    role_reserved: 'That identifier is reserved.',
    role_builtin: 'The reserved role cannot be changed.',
    role_in_use: (count = 'some') => `${count} account(s) still hold this role.`,
    role_bound: 'This role is bound to a slot in settings — unbind it first.',
    default_role_required: 'A default role must be set.',
    feature_disabled: 'That feature is not enabled on this workspace.',
    plan_exists: 'A plan with that name already exists.',
    plan_in_use: (plan = '', count = '') => `${count} account(s) are still subscribed to “${plan}”.`,
    plan_name_required: 'A plan name is required.',
    plan_role_required: 'Pick the role this plan grants.',
    answers_required: (field = 'A field') => `${field} is required.`,
    enquiry_not_found: 'That enquiry could not be found.',
    enquiry_exists: 'You already have an open sales enquiry — we will come back to you before you can send another.',
    invoice_not_found: 'That invoice could not be found.',
    template_not_found: 'That email template could not be found.',
    template_exists: 'A template with that name already exists.',
    template_required: 'A name, subject and body are required.',
    trigger_not_found: 'That trigger could not be found.',
    message_not_found: 'That message could not be found.',
    recipients_required: 'No recipients matched this audience.',
    email_not_configured: 'Set a sender address before sending mail.',
    plan_not_found: 'That plan is no longer available.',
    billing_unavailable: 'Billing is not connected to a payment provider yet.',
    already_subscribed: 'You are already on this plan.',
    not_subscribed: 'There is no active subscription to cancel.',
    limit_reached: (resource = '', limit = '') =>
        `You have reached the limit of ${limit} ${(RESOURCE_LABELS[resource as keyof typeof RESOURCE_LABELS] ?? resource).toLowerCase()}.`,
    project_not_found: 'That project could not be found.',
    project_locked: 'This project is being moved between realms and is read-only until the move completes.',
    project_archived: 'This project is archived. Restore it before making changes.',
    not_project_owner: 'Only the project owner can do that.',
    category_required: 'Add at least one category.',
    member_not_found: 'That member could not be found.',
    member_exists: 'That person is already a member of this project.',
    invite_not_found: 'That invitation could not be found.',
    invite_expired: 'That invitation has expired. Ask for a new one.',
    invite_exists: 'There is already a pending invitation for that address.',
    invite_email_mismatch: 'That invitation was sent to a different address.',
    invite_undeliverable: 'Email is switched off, so an invitation cannot be sent to an address without an account.',
    permission_escalation: (permission = '') =>
        `You cannot grant ${permission || 'a permission'} because you do not hold it yourself.`,
    owner_cannot_be_removed: 'The project owner cannot be removed. Transfer ownership first.',
    username_not_found: 'No account matches that name.',
    tag_in_use: (name = '', count = '') =>
        `${name} is still used by ${count} item(s). Remove it there first.`,
    owns_projects: (count = '') =>
        `Transfer or delete your ${count} project(s) before deleting your account.`,
    storage_limit_reached: 'You have reached your storage limit.',
    storage_hard_cap_exceeded: (used = '', cap = '') =>
        `This upload would take you to ${used} MB, past the hard limit for your ${cap} MB plan.`,
    project_limit_reached: (resource = '', used = '', limit = '') =>
        `You have reached the limit of ${limit} ${(RESOURCE_LABELS[resource as keyof typeof RESOURCE_LABELS] ?? resource).toLowerCase()}. Current usage: ${used} / ${limit}.`,
    realm_not_found: 'That realm could not be found.',
    realm_name_exists: 'A realm with that name already exists.',
    realm_in_use: (count = '') => `${count} project(s) still live on this realm.`,
    realm_unavailable: 'No build machine can take this project right now. Try again shortly.',
    realm_offline: 'That realm is offline.',
    migration_in_progress: 'This project is already being moved.',
    asset_type_unsupported: 'That asset type is not supported.',
    normal_map_exists: 'That texture already has a normal map.',
    upload_not_pending: 'That upload has already finished.',
    upload_token_invalid: 'That upload link is no longer valid.',
    parent_asset_not_found: 'The parent asset could not be found.',
    unknown_tag: 'That tag is not part of this project.',
    unknown_category: 'That category is not part of this project.',
    bundle_not_found: 'That bundle could not be found.',
    bundle_name_exists: 'A bundle with that name already exists.',
    bundle_name_required: 'Give the bundle a name.',
    bundle_empty: 'This bundle matches no assets. Adjust its tags before building.',
    unknown_build_tag: 'That build tag is not part of this project.',
    build_not_found: 'That build could not be found.',
    build_not_finished: 'Only a passed build can hold a build tag.',
    build_tag_unknown: 'That build tag is not part of this project.',
    build_already_claimed: 'That build has already been claimed.',
    schema_not_found: 'That schema could not be found.',
    schema_name_exists: 'A schema with that name already exists.',
    schema_in_use: 'That schema is used by a config and cannot be deleted.',
    schema_required: 'Pick a schema first.',
    schema_ref_cycle: 'Schemas cannot reference each other in a loop.',
    config_not_found: 'That config could not be found.',
    config_key_exists: 'A config with that key already exists.',
    config_values_invalid: (count = '') => `${count} value(s) do not match the schema.`,
    config_version_not_found: 'That config version could not be found.',
    rate_limited: (retry = '') =>
        retry ? `Too many attempts — try again in ${retry} seconds.` : 'Too many attempts — try again shortly.',
    email_invalid: 'Enter a valid email address.',
    magic_link_invalid: 'That sign-in link has expired or was already used. Request a new one.',
    api_key_not_found: 'That API key could not be found.',
    api_key_name_required: 'Give the key a name.',
    coupon_code_required: 'A coupon code is required.',
    coupon_value_required: 'Set a percentage or a fixed amount.',
    coupon_not_found: 'That coupon is not valid.',
    coupon_already_redeemed: 'You have already used this coupon.',
    job_not_found: 'That job could not be found.',
    job_kind_unknown: (kind = '') =>
        kind ? `No handler is registered for the job “${kind}”.` : 'No handler is registered for that job.',
    webhook_not_found: 'That webhook could not be found.',
    webhook_url_invalid: 'Enter a valid http(s) URL.',
    asset_source_not_found: 'That storage source could not be found.',
    asset_source_name_required: 'Give the source a name.',
    asset_source_config_invalid: 'Check the source configuration — a bucket is required for S3 sources.',
    asset_source_in_use: 'Reassign every file type using this source, and remove any files stored on it, first.',
    asset_not_found: 'That file could not be found.',
    asset_type_invalid: 'Unknown file type.',
    asset_type_unassigned: 'No storage source is configured for this file type yet.',
    signing_key_not_found: 'Unknown signing key.',
    signing_key_unavailable: 'The signing key could not be read. Check the key directory on the server.',
    fallback: 'Something went wrong. Please try again.',
} satisfies Record<ApiErrorCode | 'fallback', string | ((...params: string[]) => string)>

export const STRINGS = {
    errors: ERROR_MESSAGES,
    common: {
        loadFailed: 'Something went wrong while loading.',
        saveFailed: 'Something went wrong while saving.',
        noResults: 'No results',
        retry: 'Try again',
        search: 'Search',
        selectMultiple: 'Select one or more…',
        legalBack: 'Back',
        legalUpdated: (date: string) => `Last updated ${date}`,
    },

    commandPalette: {
        hint: 'Search',
        hintTitle: 'Search projects and jump anywhere',
        placeholder: 'Jump to a project, or type a command…',
        groupGo: 'Go to',
        groupProjects: 'Projects',
        groupActions: 'Actions',
        newProject: 'New project',
        openMembers: (project: string) => `Members of ${project}`,
        openProjectSettings: (project: string) => `Settings for ${project}`,
        assetCount: (n: number) => `${n} asset${n === 1 ? '' : 's'}`,
        newTask: (project: string) => `New task in “${project}”`,
        openProjects: 'Projects',
        openDashboard: 'Dashboard',
        openProfile: 'Profile',
        openAdmin: 'Administration',
        openModeration: 'Moderation',
        openBilling: 'Billing',
        openInvoices: 'Invoices',
        openEnquiries: 'Sales enquiries',
        openEmail: 'Email',
        taskCount: (n: number) => (n === 1 ? '1 task' : `${n} tasks`),
    },

    network: {
        offlineTitle: 'You are offline',
        offlineBody: 'Changes you make now will not be saved until the connection comes back.',
        backOnline: 'Back online.',
        unreachable: 'Could not reach the server. Check your connection and try again.',
    },

    crash: {
        title: 'This page hit an error',
        body: 'The rest of the app is still running — go back, or reload if it keeps happening.',
        reload: 'Reload the page',
        back: 'Go back',
        detailsLabel: 'Technical details',
        copy: 'Copy details',
        copied: 'Copied.',
    },

    validation: {
        invalid: 'This value is not valid.',
        required: 'This field is required.',
        tooLong: (max: number) => `Must be at most ${max} characters.`,
    },

    nav: {
        dashboard: 'Dashboard',
        projects: 'Projects',
        realms: 'Realms',
        profile: 'Profile',
        billing: 'Billing',
        admin: 'Admin',
        moderation: 'Moderation',
        sectionProject: 'Project',
        sectionMain: 'Workspace',
        sectionPlatform: 'Platform',
        invoices: 'Invoices',
        enquiries: 'Sales enquiries',
        email: 'Email',
    },

    pages: {
        landingTitle: 'WebGame Cloud — the all-in-one platform for HTML5 game developers',
        landingDescription: 'Upload assets, build optimized bundles, tweak live configs, and push updates to every player — from one console.',
        dashboardTitle: 'Dashboard',
        dashboardDescription: 'Your workspace at a glance.',
        projectsTitle: 'Projects',
        projectsDescription: 'Create and organize your projects and tasks.',
        projectDetailTitle: 'Project',
        projectDetailDescription: 'Project details and tasks.',
        profileTitle: 'Profile',
        profileDescription: 'Your account details, data export and deletion.',
        adminTitle: 'Administration',
        adminDescription: 'Users, access policy and platform settings.',
        invoicesTitle: 'Invoices',
        invoicesDescription: 'Invoices issued to accounts on this workspace.',
        billingTitle: 'Billing',
        billingDescription: 'Your plan, invoices and upgrades.',
        emailTitle: 'Email',
        emailDescription: 'Templates, triggers and the outbox.',
        enquiriesTitle: 'Sales enquiries',
        enquiriesDescription: 'Plan applications waiting for a sales follow-up.',
        publicInvoiceTitle: 'Invoice',
        publicInvoiceDescription: 'Printable invoice.',
        moderationTitle: 'Moderation',
        moderationDescription: 'Reports queue and the audit log.',
        privacyTitle: 'Privacy Policy',
        termsTitle: 'Terms of Service',
        loginTitle: 'Sign in',
    },

    waitlist: {
        eyebrow: 'Early access',
        eyebrowReserved: 'Reserved',
        title: 'Claim 250 MB. Keep it forever.',
        subtitle:
            'Sign up before launch and your free tier stays at 250 MB — enough for a first prototype\'s art, audio and configs, on us.',
        railCaption: '25 blocks · 10 MB each',
        railTotal: '250 MB free tier',
        emailLabel: 'Email address',
        emailPlaceholder: 'you@studio.gg',
        emailInvalid: 'Enter a valid email address.',
        cta: 'Reserve my 250 MB',
        ctaBusy: 'Reserving…',
        consent: 'Email me product updates. One message when the console opens, nothing else.',
        benefitList: [
            '250 MB free tier — for life, not a trial.',
            'One email, the day the console opens. No newsletters.',
            'No tracking, no resale. Your address stays on the launch list.',
        ],
        helper: 'We email you once — the day the console opens.',
        thanks: 'Reserved. Check your inbox.',
        thanksDetail: (email: string) => `We saved 250 MB against ${email}.`,
        failed: 'That did not go through. Try again.',
        statLabel: 'developers reserved',
    },

    landing: {
        announceText: 'Building a browser game? Come hang out with us on Discord.',
        announceCta: 'Join the Discord',

        eyebrow: 'The all-in-one platform for HTML5 game developers',
        heroTitle: 'Ship HTML5 games faster, from one console',
        heroDescription:
            'Upload assets, build optimized bundles, tweak live configs, and push updates to every player — all from one dashboard. The backend your game needs, without building it yourself.',
        heroNote: 'In alpha — join the early access list below.',
        ctaPrimary: 'Get early access',
        ctaSecondary: 'See features',
        ctaDashboard: 'Open console',

        metrics: [
            { key: 'uptime', value: '99.99%', label: 'global uptime', helper: 'multi-region edge CDN' },
            { key: 'rollout', value: '< 5s', label: 'live rollouts', helper: 'config change to player' },
        ],
        metricsUptimeCaption: '90 days · no incident',
        metricsRolloutFrom: 'console',
        metricsRolloutTo: 'player',

        howEyebrow: 'How it works',
        howTitle: 'From raw assets to live players, in one console',
        howLead:
            'Six stages that replace the patchwork of buckets, build scripts, CDNs, config services, and ad-hoc tooling most studios stitch together — whether you ship slots, playables, or full HTML5 titles.',

        howTabs: [
            {
                key: 'games',
                label: 'HTML5 Games',
                icon: 'gamepad-2',
                assets: [
                    { icon: 'Image', name: 'hero_atlas.png', size: '2.4 MB', tags: ['ui', 'menu'] },
                    { icon: 'Music', name: 'boss_theme.ogg', size: '1.1 MB', tags: ['audio', 'level-7'] },
                    { icon: 'FileJson', name: 'enemies.json', size: '14 KB', tags: ['config', 'gameplay'] },
                    { icon: 'Image', name: 'tileset_forest.png', size: '3.7 MB', tags: ['world', 'level-3'] },
                ],
                bundleName: 'bundle_v0.42',
                bundleMeta: 'status: pass · 12.4 MB · 38.2s',
                chips: ['PixiJS', 'MaxRects', 'Rotation', 'Downscale 75%'],
                pipeline: [
                    { title: 'Upload', sub: 'raw assets' },
                    { title: 'Filter', sub: 'pick & tag' },
                    { title: 'Build', sub: 'optimize' },
                    { title: 'Deploy', sub: 'go live' },
                    { title: 'Rollback', sub: 'one click' },
                ],
                config: [
                    { key: 'boss.health', value: '1200', live: true },
                    { key: 'drop.legendary_rate', value: '0.04', live: true },
                    { key: 'event.spring_sale', value: 'true', live: false },
                    { key: 'shop.currency', value: 'gems', live: false },
                ],
                team: [
                    { name: 'Ava Marek', email: 'ava@studio.gg', role: 'Lead engineer' },
                    { name: 'Jonas Reid', email: 'jonas@studio.gg', role: 'Art director' },
                    { name: 'Kira Oduya', email: 'kira@studio.gg', role: 'Game designer' },
                    { name: 'Sam Pike', email: 'sam@studio.gg', role: 'Producer' },
                ],
                stages: [
                    { eyebrow: '01 — Asset library', title: 'Upload, tag, and organize every asset', description: 'Drag in textures, audio, JSON, and configs. Tag and group them by scene, level, or feature so the right artist or engineer always finds the right file.' },
                    { eyebrow: '02 — Optimized builds', title: 'Create build-ready bundles in seconds', description: 'Pick what ships, pick the engine, and we crunch it into a CDN-optimized bundle — compressed, deduped, and split for the fastest possible load.' },
                    { eyebrow: '03 — End-to-end pipeline', title: 'Upload → filter → build → deploy → rollback', description: 'One pipeline from raw asset to live player. Promote builds across environments, ship to production with a click, and roll back the moment something looks off.' },
                    { eyebrow: '04 — Live config', title: 'Type-safe live tweaks, no redeploys', description: 'Adjust drop rates, flip a feature flag, retune a boss — and push it to every player in seconds. Schemas keep configs type-safe so you ship changes, not bugs.' },
                    { eyebrow: '05 — Studio collaboration', title: 'Invite your whole studio', description: 'Bring designers, artists, engineers, and producers into one workspace. Per-member permissions and an audit trail keep everyone in sync.' },
                    { eyebrow: '06 — CDN distribution', title: 'Edge delivery to every region your players live in', description: 'Bundles and configs replicate to a multi-region edge network within seconds of publish, so a player in Tokyo loads the same build as one in Berlin — both fast.' },
                ],
            },
            {
                key: 'igaming',
                label: 'iGaming',
                icon: 'dices',
                assets: [
                    { icon: 'Image', name: 'reel_symbols.png', size: '1.8 MB', tags: ['reels', 'base-game'] },
                    { icon: 'Music', name: 'win_fanfare.ogg', size: '820 KB', tags: ['audio', 'bonus'] },
                    { icon: 'FileJson', name: 'paytable.json', size: '9 KB', tags: ['math', 'certified'] },
                    { icon: 'Image', name: 'bonus_frame.png', size: '2.1 MB', tags: ['bonus', 'ui'] },
                ],
                bundleName: 'slot_v3.11',
                bundleMeta: 'status: pass · 8.9 MB · 26.4s',
                chips: ['Phaser', 'MaxRects', 'Locale x9', 'Downscale 90%'],
                pipeline: [
                    { title: 'Upload', sub: 'certified art' },
                    { title: 'Filter', sub: 'per market' },
                    { title: 'Build', sub: 'per operator' },
                    { title: 'Deploy', sub: 'go live' },
                    { title: 'Rollback', sub: 'one click' },
                ],
                config: [
                    { key: 'rtp.profile', value: '96.2', live: true },
                    { key: 'bet.max_multiplier', value: '250', live: true },
                    { key: 'jackpot.enabled', value: 'true', live: false },
                    { key: 'locale.default', value: 'en-GB', live: false },
                ],
                team: [
                    { name: 'Rhea Colombo', email: 'rhea@studio.gg', role: 'Math lead' },
                    { name: 'Dmitri Vela', email: 'dmitri@studio.gg', role: 'Compliance' },
                    { name: 'Nina Farr', email: 'nina@studio.gg', role: 'Art director' },
                    { name: 'Owen Blake', email: 'owen@studio.gg', role: 'Account manager' },
                ],
                stages: [
                    { eyebrow: '01 — Asset library', title: 'Certified art, audio, and paytables in one library', description: 'Keep every reel strip, fanfare, and paytable in one place, tagged by market and certification round so nothing unapproved reaches a build.' },
                    { eyebrow: '02 — Optimized builds', title: 'One title, one bundle per operator', description: 'Select by tag and produce a bundle per operator or market — same source assets, different packs, no duplicated projects.' },
                    { eyebrow: '03 — End-to-end pipeline', title: 'Upload → filter → build → deploy → rollback', description: 'Every build is traceable from the asset it came from to the operator it shipped to, and a rollback is a single click on the previous tag.' },
                    { eyebrow: '04 — Live config', title: 'Retune limits without a certification round', description: 'Bet limits, jackpot switches, and locale defaults live in schema-checked configs you can change per market in seconds.' },
                    { eyebrow: '05 — Studio collaboration', title: 'Math, compliance, and art in one workspace', description: 'Give compliance read access and artists write access to the categories they own — permissions are per member, not per role.' },
                    { eyebrow: '06 — CDN distribution', title: 'Every market served from its nearest edge', description: 'Publish once and the same certified build answers from the region each operator plays in, with configs following within seconds.' },
                ],
            },
            {
                key: 'playables',
                label: 'Playable Ads',
                icon: 'megaphone',
                assets: [
                    { icon: 'Image', name: 'endcard_q2.png', size: '0.4 MB', tags: ['creative', 'campaign-x'] },
                    { icon: 'Music', name: 'cta_tap.ogg', size: '46 KB', tags: ['audio', 'cta'] },
                    { icon: 'FileJson', name: 'copy_variants.json', size: '6 KB', tags: ['config', 'ab'] },
                    { icon: 'Image', name: 'sprites_hero.png', size: '0.8 MB', tags: ['creative', 'gameplay'] },
                ],
                bundleName: 'playable_q2_v7',
                bundleMeta: 'status: pass · 4.6 MB · 22.4s',
                chips: ['≤ 5 MB', 'AppLovin', 'Meta', 'MRAID 3.0'],
                pipeline: [
                    { title: 'Upload', sub: 'creatives' },
                    { title: 'Variant', sub: 'A/B build' },
                    { title: 'Build', sub: 'size-gate' },
                    { title: 'Ship', sub: 'to networks' },
                    { title: 'Hot-swap', sub: 'mid-campaign' },
                ],
                config: [
                    { key: 'ab.variant', value: 'B', live: true },
                    { key: 'cta.url', value: 'https://…', live: true },
                    { key: 'difficulty.curve', value: '0.7', live: false },
                    { key: 'campaign.live', value: 'true', live: false },
                ],
                team: [
                    { name: 'Uma Aster', email: 'uma@studio.gg', role: 'UA manager' },
                    { name: 'Cleo Lund', email: 'cleo@studio.gg', role: 'Creative lead' },
                    { name: 'Eli Nakamura', email: 'eli@studio.gg', role: 'Engineer' },
                    { name: 'Ana Ruiz', email: 'ana@studio.gg', role: 'Analyst' },
                ],
                stages: [
                    { eyebrow: '01 — Asset library', title: 'Creatives, end-cards, and variant copy', description: 'Upload creatives, end-card art, CTA audio, and variant copy. Tag by campaign and variant so UA managers always grab the right asset.' },
                    { eyebrow: '02 — Optimized builds', title: 'Crunch under every network size ceiling', description: 'One source, many network packages. Each build is crunched under the network ceiling automatically — no more manual byte-shaving.' },
                    { eyebrow: '03 — End-to-end pipeline', title: 'Upload → variant → build → ship → hot-swap', description: 'One pipeline from creative to live ad unit. Build A/B variants under the size gate, ship to every network, and hot-swap the creative mid-campaign.' },
                    { eyebrow: '04 — Live config', title: 'Flip variants and retune mid-campaign', description: 'Change the A/B variant, swap the CTA target, or retune difficulty mid-campaign and push it to every impression in seconds.' },
                    { eyebrow: '05 — Studio collaboration', title: 'UA, creative, and devs in one workspace', description: 'Bring UA managers, creative leads, engineers, and analysts into one campaign workspace with an audit trail on every iteration.' },
                    { eyebrow: '06 — CDN distribution', title: 'Edge-served so the playable opens instantly', description: 'Playables and their configs replicate to a multi-region edge within seconds of publish, so the unit opens instantly in every geo the campaign runs.' },
                ],
            },
        ],

        enginesEyebrow: 'Bring your own engine',
        enginesTitle: 'It ships whatever you build with',
        enginesLead:
            'We pack the assets and serve the build. Your engine, your code, your repo — nothing to rewrite.',
        engines: [
            {
                key: 'phaser',
                name: 'Phaser',
                note: 'atlas + audio sprites',
                detail: 'Ship your texture atlas and audio sprite map as they are. We pack them, hash them, and hand the game one manifest to load.',
                tags: ['atlas.json', 'audiosprite', 'scenes'],
            },
            {
                key: 'pixi',
                name: 'PixiJS',
                note: 'spritesheet packing',
                detail: 'Textures are grouped, trimmed and packed into spritesheets sized for the devices you actually ship to — no manual re-export.',
                tags: ['spritesheet', 'mipmaps', 'webp'],
            },
            {
                key: 'canvas',
                name: 'Plain canvas',
                note: 'anything static',
                detail: 'No engine, no bundler, no framework. Upload the files, tag them, and the edge serves them with the right cache headers.',
                tags: ['static', 'no build', 'edge cache'],
            },
        ],

        faqEyebrow: 'Before you ask',
        faqTitle: 'The questions every dev asks first',
        faqLead: 'Straight answers. If something is missing, ask us on Discord and we will add it here.',
        faq: [
            {
                q: 'Do I need a card to start?',
                a: 'No. The free tier needs an email and nothing else. You only see a payment form if you outgrow it and choose to upgrade.',
            },
            {
                q: 'What happens to my games if I stop paying?',
                a: 'Your builds keep serving on the free tier limits. Nothing is deleted, and you can export every asset you uploaded at any time.',
            },
            {
                q: 'Can I use it with an engine you have not listed?',
                a: 'Yes. A bundle is just tagged files packed to your rules, so anything that loads assets over HTTP works — the engine list is about presets, not support.',
            },
            {
                q: 'How fast is a config change live?',
                a: 'Under five seconds to the edge. Configs are versioned per build tag, so you can change balance for beta players without touching what release players load.',
            },
            {
                q: 'Is my game visible to anyone before I launch?',
                a: 'Only to people you invite. Builds are private to the project until you tag one for release.',
            },
        ],

        featuresEyebrow: 'Platform features',
        featuresTitle: 'Everything your studio needs to ship a game',
        featuresIntro:
            'From the first asset upload to the build players are loading right now — every tool your team uses, in one console.',
        featuresDiagramAlt:
            'Textures, audio and data files feed into the webgame.cloud server stack, which packs them into one optimized bundle and serves it from the edge to players on desktop, console and mobile.',
        featuresPrimaryCta: 'Get early access',
        featuresSecondaryCta: 'See the flow',
        features: [
            { icon: 'Image', eyebrow: 'Asset library', title: 'All your assets, in one place', description: 'Drag in art, sounds, configs, and shaders. Group them into categories that make sense to your team, tag them however you like, and find anything in seconds.' },
            { icon: 'Type', eyebrow: 'Bitmap fonts & dialogues', title: 'Write text. Tune fonts. Right in the console.', description: 'Fonts and dialogue files travel with the build like any other asset group — no extra tools for the team to learn.' },
            { icon: 'Languages', eyebrow: 'Localization', title: 'A home base for translators', description: 'Locale files ship as their own build group, swappable without a rebuild. No more emailing spreadsheets.' },
            { icon: 'Sliders', eyebrow: 'Configs & schemas', title: 'Configs designers can edit without breaking things', description: 'Define what a config looks like once. Designers fill it in through a generated editor that catches mistakes before they ship.' },
            { icon: 'Package', eyebrow: 'Optimized builds', title: 'Builds tuned for the engines you use', description: 'A bundle is a saved tag query — re-tag a file and every bundle that matches follows it. Pick the engine, hit build, and let the console do the work.' },
            { icon: 'Hammer', eyebrow: 'Build lifecycle', title: 'Keep the builds that matter, drop the rest', description: 'Tag the builds you want to keep — release, beta, whatever fits — and clear out the rest in one click. Promote or roll back without rebuilding.' },
            { icon: 'LayoutDashboard', eyebrow: 'Project dashboard', title: 'Project health at a glance', description: 'Every project opens to a clean overview — recent builds, what is inside, who is on the team.' },
            { icon: 'Users', eyebrow: 'Studio collaboration', title: 'Your whole team, with the right access', description: 'Invite teammates by email and grant exactly the permissions they need. Everyone signs in with Discord, GitHub, or Google.' },
            { icon: 'CreditCard', eyebrow: 'Plans, billing & usage', title: 'Plans, storage, invoices — all here', description: 'Start free. Upgrade when you outgrow it. Your usage, plan, and invoice history all live in the console.' },
        ],

        pricingEyebrow: 'Pricing',
        pricingTitle: 'Plans that grow with your game',
        pricingIntro:
            'Start free and upgrade as your team and player base grow. Every plan includes the full console, CDN delivery, and the build pipeline.',
        pricingContact: 'Contact sales',
        pricingStart: 'Get early access',
        pricingFairUse: "Bandwidth fair-use; we'll reach out before any throttle.",

        footerTagline: 'WEBGAME.CLOUD',
        footerDescription: 'The all-in-one console for HTML5 game developers.',
        footerProduct: 'Product',
        footerCommunity: 'Community',
        footerContact: 'Contact',
        footerLegal: 'Legal',
        footerSignIn: 'Get early access',
        footerDashboard: 'Open console',
        footerCta: 'Get early access',
        footerCtaHeading: 'Sign up early. Keep 250 MB free, forever.',
        footerCtaDescription: 'One email, sent the day the console goes live.',
        footerHowItWorks: 'How it works',
        footerFeatures: 'Features',
        footerPricing: 'Pricing',
        footerEarlyAccess: 'Early access',
        footerGithub: 'GitHub',
        footerDiscord: 'Discord',
        footerHelloEmail: 'hello@webgame.cloud',
        footerSupportEmail: 'support@webgame.cloud',
        footerTerms: 'Terms of Service',
        footerPrivacy: 'Privacy Policy',
        footerDmca: 'DMCA',
        footerLegalLine: '© 2026 webgame.cloud — All rights reserved',
    },

    auth: {
        title: 'Sign in',
        subtitle: 'Sign in to your account.',
        heroEyebrow: 'Starter Template',
        heroTitle: 'Ship HTML5 games faster',
        heroSubtitle:
            'Authentication, user management, roles & feature flags, notifications and a worked example feature — ready to build on.',
        signInWith: (provider: string) => `Continue with ${provider}`,
        loginAsOwner: 'Log in as owner',
        devTitle: 'Developer sign-in',
        devHint: 'Email-only sign-in for local development. The first account ever created becomes the owner.',
        emailPlaceholder: 'you@example.com',
        namePlaceholder: 'Display name (optional)',
        signIn: 'Sign in',
        signOut: 'Sign out',
        ssoFailed: 'Sign-in failed. Please try again.',
        ssoDeactivated: 'This account has been deactivated.',
        footerTagline: 'Assets in, published builds out.',
        ecosystem: {
            title: 'Everything already wired in',
            coreName: 'WebGame Cloud',
            coreLabel: 'console',
            rings: [
                {
                    label: 'Platform',
                    items: [
                        { name: 'Auth & SSO' },
                        { name: 'Roles & flags' },
                        { name: 'User admin' },
                    ],
                },
                {
                    label: 'Product',
                    items: [
                        { name: 'Asset library' },
                        { name: 'Bundles & builds' },
                        { name: 'Live configs' },
                        { name: 'Build realms' },
                    ],
                },
            ],
        },
    },

    account: {
        legalTitle: 'Legal',
        legalPrivacy: 'Privacy Policy',
        legalTerms: 'Terms of Service',
        exportTitle: 'Export your data',
        exportDescription: 'Download everything you own as a JSON file.',
        exportAction: 'Export data',
        deleteTitle: 'Delete account',
        deleteDescription: 'Permanently remove your account and everything you own. This cannot be undone.',
        deleteAction: 'Delete account',
        deleteOwnerBlocked: 'The owner account cannot be deleted while it holds the owner role. Hand the role over first.',
    },

    profile: {
        title: 'Profile',
        intro: 'Edit your display name, export your data or delete your account — everything else comes from your sign-in provider or is set by an administrator.',
        nameLabel: 'Display name',
        emailLabel: 'Email',
        roleLabel: 'Role',
        membersLabel: 'Members',
        variablesTitle: 'Template fields',
        variablesHint: 'Fill the placeholders this template uses.',
        joinedLabel: 'Joined',
        statusLabel: 'Status',
        statusActive: 'Active',
        statusInactive: 'Deactivated',
        verifiedBadge: 'Verified',
        save: 'Save',
        connectionsTitle: 'Connected accounts',
        connectionsIntro: 'Sign in with any of these — they all open the same account.',
        connectedAs: (email: string) => (email ? `Connected as ${email}` : 'Connected'),
        notConnected: 'Not connected',
        connect: 'Connect',
        disconnect: 'Disconnect',
        lastIdentityHint: 'Your only sign-in method cannot be disconnected.',
        tabAccount: 'Account',
        tabDevices: 'Devices',
    },

    billing: {
        title: 'Subscription',
        intro: 'Your plan and what it unlocks.',
        currentPlanTitle: 'Current plan',
        freePlanName: 'Free',
        freePlanHint: 'The plan every account starts on — no payment required.',
        plansTitle: 'Plans',
        statusLabel: 'Status',
        renewsLabel: 'Renews',
        endsLabel: 'Ends',
        startedLabel: 'Started',
        planLabel: 'Plan',
        subscribe: 'Choose plan',
        currentBadge: 'Current',
        cancel: 'Cancel subscription',
        cancelPending: 'Cancels at period end',
        notConnectedTitle: 'No plans available',
        notConnectedHint: 'No plans are published yet. An administrator creates them in Access & limits.',
        unavailableTitle: 'Upgrades are currently unavailable',
        contactSalesTitle: 'Talk to us to get this plan',
        contactSalesHint: 'This plan is assigned by our team. Get in touch and we will set it up for your account.',
        contactSalesAction: 'Contact sales',
        contactSalesMissing: 'No sales contact has been configured yet — ask an administrator.',
        modeManual: 'Assigned by sales',
        modeManaged: 'Self-serve checkout',
        tabSubscription: 'Subscription',
        tabInvoices: 'Invoices',
        invoicesTitle: 'Your invoices',
        invoicesIntro: 'Every invoice issued to your account.',
        invoicesEmpty: 'No invoices yet.',
        invoicePreview: 'Preview',
        perMonth: '/ month',
        perYear: '/ year',
        freePrice: 'Free',
        currentPlanBadge: 'Your plan',
        enquiryTitle: (plan: string) => `Apply for ${plan}`,
        enquiryIntro: 'Tell us about your needs and our team will set the plan up for your account.',
        enquirySubmit: 'Send application',
        enquiryCancel: 'Cancel',
        enquiryContactHint: (contact: string) => `Prefer email? Write to ${contact}.`,
        statusLabels: {
            none: 'No subscription',
            trialing: 'Trial',
            active: 'Active',
            past_due: 'Past due',
            canceled: 'Canceled',
        },
        price: (amount: string, interval: string) => `${amount} / ${interval}`,
        enquiryPendingAction: 'Request sent',
        enquiryPendingHint: (plan: string, status: string) =>
            `Your request for ${plan} is with our team (${status}). You can send another once it is closed.`,
        enquiryStatusLabels: {
            new: 'received',
            contacted: 'in progress',
            won: 'won',
            lost: 'closed',
        } as Record<string, string>,
        intervalMonth: 'month',
        intervalYear: 'year',
    },

    plansAdmin: {
        title: 'Plans',
        intro: 'Plans a subscription can put an account on. Each plan grants a role — bind it below in Slots.',
        create: 'New plan',
        nameLabel: 'Plan name',
        descriptionLabel: 'Description',
        priceLabel: 'Price (cents)',
        currencyLabel: 'Currency',
        intervalLabel: 'Billing interval',
        modeLabel: 'How it is sold',
        roleLabel: 'Role granted',
        activeLabel: 'Published',
        save: 'Save plan',
        delete: 'Delete plan',
        cancel: 'Cancel',
        empty: 'No plans yet.',
        unpublished: 'Unpublished',
        deletePrompt: (name: string) => `Delete the plan “${name}”?`,
        modeManual: 'Manual — sales assigns it',
        modeManaged: 'Managed — payment gateway',
        modeHint: 'Manual plans collect an application and are assigned by your team. Managed plans check out through the payment gateway.',
        roleHint: 'The role an active subscription on this plan grants.',
        intervalMonth: 'Monthly',
        intervalYear: 'Yearly',
        featuresLabel: 'Features',
        featuresHint: 'One per line — shown on the pricing card.',
        salesFieldsLabel: 'Application fields',
        salesFieldsHint: 'What a manual plan asks for when an account applies.',
        fieldLabelLabel: 'Question',
        fieldLabelPlaceholder: 'e.g. Company',
        fieldTypeLabel: 'Answer type',
        fieldRequiredLabel: 'Required',
        fieldRemove: 'Remove',
        fieldAdd: 'Add field',
        fieldsEmpty: 'No application fields yet — accounts will just send a plain request.',
        fieldTypes: {
            text: 'Short text',
            textarea: 'Long text',
            email: 'Email',
            number: 'Number',
        },
        activeHint: 'Unpublished plans stay hidden from accounts.',
        edit: 'Edit',
        slotLabel: (name: string) => `Plan: ${name}`,
        slotHint: (mode: string) => `The role an active subscription on this plan grants (${mode}).`,
    },

    enquiries: {
        title: 'Sales enquiries',
        intro: 'Applications submitted for plans that sales assigns.',
        columnAccount: 'Account',
        columnPlan: 'Plan',
        columnStatus: 'Status',
        columnDetails: 'Details',
        columnCreated: 'Received',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Name, email or answer',
        filterStatus: 'Status',
        filterPlan: 'Plan',
        filterAll: 'All',
        passedOf: 'passed of',
        buildWord: 'build',
        buildsWord: 'builds',
        taggedCount: (n: number) => `${n} tagged`,
        empty: 'No sales enquiries yet.',
        emptyFiltered: 'No enquiries match these filters.',
        markContacted: 'Contacted',
        markWon: 'Won',
        markLost: 'Lost',
        openTrail: 'Audit trail',
        openAction: 'Add action',
        trailTitle: 'Audit trail',
        trailEmpty: 'Nothing recorded yet.',
        trailKinds: {
            created: 'Application received',
            status: 'Status changed',
            note: 'Note added',
            invoice: 'Invoice created',
        },
        actionTitle: 'Add action',
        actionKindLabel: 'Action',
        actionKindStatus: 'Change status',
        actionKindNote: 'Add a note',
        actionKindInvoice: 'Create an invoice',
        actionStatusLabel: 'New status',
        actionNoteLabel: 'Note',
        actionAmountLabel: 'Amount (cents)',
        actionCurrencyLabel: 'Currency',
        actionAmountHint: 'Leave empty to use the plan price.',
        actionSubmit: 'Record action',
        actionCancel: 'Cancel',
        statusLabels: {
            new: 'New',
            contacted: 'Contacted',
            won: 'Won',
            lost: 'Lost',
        },
    },

    publicInvoice: {
        title: 'Invoice',
        billedTo: 'Billed to',
        issued: 'Issued',
        due: 'Due',
        paid: 'Paid',
        plan: 'Plan',
        amount: 'Amount due',
        status: 'Status',
        print: 'Print',
        notFound: 'This invoice link is not valid.',
        thanks: 'Thank you for your business.',
    },

    invoices: {
        title: 'Invoices',
        intro: 'Every invoice issued on this workspace.',
        columnNumber: 'Invoice',
        columnUser: 'Account',
        columnPlan: 'Plan',
        columnStatus: 'Status',
        columnAmount: 'Amount',
        columnIssued: 'Issued',
        columnProvider: 'Provider',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Number, name or email',
        filterStatus: 'Status',
        filterPlan: 'Plan',
        filterProvider: 'Provider',
        filterFrom: 'Issued from',
        filterTo: 'Issued to',
        filterAll: 'All',
        passedOf: 'passed of',
        buildWord: 'build',
        buildsWord: 'builds',
        taggedCount: (n: number) => `${n} tagged`,
        empty: 'No invoices yet.',
        emptyFiltered: 'No invoices match these filters.',
        markPaid: 'Mark paid',
        markVoid: 'Void',
        view: 'View',
        statusLabels: {
            draft: 'Draft',
            open: 'Open',
            paid: 'Paid',
            void: 'Void',
            uncollectible: 'Uncollectible',
        },
    },

    email: {
        tabOutbox: 'Outbox',
        tabTemplates: 'Templates',
        tabTriggers: 'Triggers',
        tabSettings: 'Delivery',

        settingsTitle: 'Email delivery',
        settingsIntro: 'Where transactional and scheduled mail is sent from.',
        providerLabel: 'Provider',
        providerLog: 'Log only (development)',
        providerSmtp: 'SMTP server',
        providerMailchimp: 'Mailchimp (Mandrill)',
        fromNameLabel: 'Sender name',
        fromEmailLabel: 'Sender address',
        smtpHostLabel: 'SMTP host',
        smtpPortLabel: 'SMTP port',
        smtpUserLabel: 'SMTP username',
        smtpPasswordLabel: 'SMTP password',
        smtpSecureLabel: 'Use TLS (port 465)',
        mailchimpKeyLabel: 'Mandrill API key',
        secretSet: 'Saved — leave blank to keep it.',
        batchSizeLabel: 'Batch size',
        batchSizeHint: 'How many messages the worker sends per tick.',
        save: 'Save',
        sendTest: 'Send test email',
        testQueued: 'Test email queued.',

        outboxTitle: 'Outbox',
        outboxIntro: 'Everything queued, sent or failed on this workspace.',
        outboxEmpty: 'Nothing queued yet.',
        columnTo: 'To',
        columnSubject: 'Subject',
        columnStatus: 'Status',
        columnTemplate: 'Template',
        columnScheduled: 'Scheduled',
        columnAttempts: 'Tries',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Address, subject or body',
        filterStatus: 'Status',
        filterTemplate: 'Template',
        filterAll: 'All',
        passedOf: 'passed of',
        buildWord: 'build',
        buildsWord: 'builds',
        taggedCount: (n: number) => `${n} tagged`,
        retry: 'Retry',
        cancel: 'Cancel',
        statusLabels: {
            queued: 'Queued',
            sending: 'Sending',
            sent: 'Sent',
            failed: 'Failed',
            canceled: 'Canceled',
        },

        composeTitle: 'Compose email',
        compose: 'Compose',
        audienceLabel: 'Audience',
        audienceSelf: 'Just me (test)',
        audienceCustom: 'Specific addresses',
        audienceAllUsers: 'Every active account',
        audienceRole: 'Everyone with a role',
        audienceMembers: 'Selected members',
        roleLabel: 'Role',
        membersLabel: 'Members',
        variablesTitle: 'Template fields',
        variablesHint: 'Fill the placeholders this template uses.',
        emailsLabel: 'Addresses',
        emailsHint: 'Comma separated.',
        templateLabel: 'Template',
        templateNone: 'No template — write it below',
        subjectLabel: 'Subject',
        bodyLabel: 'Body',
        bodyHint: 'Placeholders: {{workspace}}, {{recipientName}}, {{recipientEmail}}, {{date}}.',
        scheduleLabel: 'Send at',
        scheduleHint: 'Leave empty to send on the next worker tick.',
        send: 'Queue email',
        queued: (count: number) => `${count} message${count === 1 ? '' : 's'} queued.`,

        templatesTitle: 'Templates',
        templatesIntro: 'Reusable subjects and bodies for triggers and campaigns.',
        templatesEmpty: 'No templates yet.',
        newTemplate: 'New template',
        editTemplate: 'Edit',
        templateNameLabel: 'Name',
        templateDescriptionLabel: 'Description',
        templateActiveLabel: 'Active',
        templatePreview: 'Preview',
        templateDelete: 'Delete template',
        templateDeletePrompt: (name: string) => `Delete the template “${name}”?`,
        templateSaved: 'Template saved.',

        triggersTitle: 'Audit triggers',
        triggersIntro: 'Send a template whenever an audited action happens.',
        triggersEmpty: 'No triggers yet — every audited action is available.',
        triggerAction: 'Audit action',
        triggerTemplate: 'Template',
        triggerRecipient: 'Send to',
        triggerRecipientActor: 'The account that acted',
        triggerRecipientRole: 'Platform role',
        triggerRecipientMembers: 'Selected members',
        triggerRecipientCustom: 'Fixed addresses',
        triggerRoleLabel: 'Role',
        triggerMembersLabel: 'Members',
        triggerCustomEmail: 'Addresses',
        triggerActive: 'Active',
        triggerAdd: 'Add trigger',
        triggerDelete: 'Delete',
        triggerSaved: 'Trigger saved.',
    },

    featureFlags: {
        title: 'Feature flags',
        intro: 'Turn optional parts of the product on or off for the whole workspace.',
        labels: {
            billing: 'Subscriptions & billing',
            email: 'Email delivery',
            magic_link: 'Magic-link sign-in',
            files: 'File uploads',
        },
        hints: {
            billing: 'Exposes plans, the subscription screen and the billing API. Leave off until a payment provider is connected.',
            email: 'Exposes templates, the outbox and the send worker. Leave off until a provider is configured.',
            magic_link: 'Lets people sign in with a one-time link mailed to them. Needs Email delivery on — the link has no way out otherwise.',
            files: 'Exposes file storage sources and the upload API. Leave off until at least one source is configured.',
        },
        requiresLabel: (flag: string) => `Requires ${flag}`,
    },

    signingKeys: {
        tab: 'Signing keys',
        title: 'Token signing keys',
        intro: 'Key pairs this workspace uses to sign JWTs for other services. The private key never leaves the server — hand the public key to whoever validates the token.',
        empty: 'No signing keys are defined.',
        algorithmLabel: 'Algorithm',
        kidLabel: 'Key ID',
        createdLabel: 'Created',
        publicKeyLabel: 'Public key',
        publicKeyHint: 'Give this to the service that validates tokens signed with this key.',
        showPublicKey: 'Show public key',
        copy: 'Copy',
        copied: 'Copied.',
        close: 'Close',
        rotate: 'Rotate',
        rotateConfirm: 'Rotate key',
        rotatePrompt: (label: string) => `Rotate “${label}”? New tokens use the new key immediately. Tokens already issued stay valid until they expire, so keep the retired public key published until then.`,
        rotated: 'Signing key rotated.',
        rotateFailed: 'Could not rotate the signing key.',
        retired: (count: number) => `${count} retired key${count === 1 ? '' : 's'}`,
        retiredHint: 'Previous public keys are kept so tokens issued before the rotation can still be validated.',
    },

    apiKeys: {
        tab: 'API keys',
        title: 'API keys',
        intro: 'Tokens for scripts and integrations. A key acts as you, limited to the scopes you pick.',
        empty: 'No API keys yet.',
        create: 'New key',
        nameLabel: 'Name',
        namePlaceholder: 'CI deploy bot',
        scopesLabel: 'Scopes',
        scopesHint: 'Leave empty to grant everything the account can do. A scope you do not hold is ignored.',
        expiresLabel: 'Expires',
        expiresHint: 'Leave empty for a key that never expires.',
        revoke: 'Revoke',
        revokePrompt: (name: string) => `Revoke “${name}”? Anything using it stops working immediately.`,
        created: 'API key created.',
        revoked: 'API key revoked.',
        saveFailed: 'Could not save the API key.',
        tokenTitle: 'Copy this key now',
        tokenHint: 'This is the only time the full key is shown. Store it somewhere safe.',
        copy: 'Copy',
        copied: 'Copied.',
        done: 'Done',
        lastUsed: (when: string) => `Last used ${when}`,
        neverUsed: 'Never used',
        expires: (when: string) => `Expires ${when}`,
        neverExpires: 'No expiry',
        scopeCount: (n: number) => (n === 0 ? 'Full account access' : `${n} scope${n === 1 ? '' : 's'}`),
    },

    webhooks: {
        tab: 'Webhooks',
        title: 'Endpoints',
        intro: 'POST every audited action to your own services. Payloads are signed with HMAC-SHA256.',
        empty: 'No endpoints yet.',
        create: 'New endpoint',
        edit: 'Edit',
        delete: 'Delete',
        deletePrompt: (url: string) => `Delete the endpoint “${url}” and its delivery history?`,
        urlLabel: 'Endpoint URL',
        urlPlaceholder: 'https://example.com/hooks/appkit',
        descriptionLabel: 'Description',
        eventsLabel: 'Events',
        eventsHint: 'Audited actions to stream. Leave empty and nothing is sent.',
        activeLabel: 'Active',
        secretLabel: 'Signing secret',
        secretHint: 'Leave empty to keep the current secret. A new one is generated on create.',
        secretSet: 'A signing secret is set.',
        saved: 'Endpoint saved.',
        deleted: 'Endpoint deleted.',
        saveFailed: 'Could not save the endpoint.',
        deliveriesTitle: 'Deliveries',
        deliveriesIntro: 'Every attempt, newest first. Failed deliveries retry with backoff on the job queue.',
        deliveriesEmpty: 'No deliveries yet.',
        columnEndpoint: 'Endpoint',
        columnEvent: 'Event',
        columnStatus: 'Status',
        columnAttempts: 'Attempts',
        columnResponse: 'Response',
        columnCreated: 'Sent',
        filterStatus: 'Status',
        filterAll: 'All',
        passedOf: 'passed of',
        buildWord: 'build',
        buildsWord: 'builds',
        taggedCount: (n: number) => `${n} tagged`,
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Event, URL or error',
        statusLabels: {
            pending: 'Pending',
            delivered: 'Delivered',
            failed: 'Failed',
        } as Record<string, string>,
        eventCount: (n: number) => `${n} event${n === 1 ? '' : 's'}`,
        inactive: 'Paused',
    },

    files: {
        tab: 'Files',
        title: 'Storage sources',
        intro: 'Where uploaded files are written. Create as many as you need — different disks, different buckets.',
        empty: 'No storage sources yet.',
        emptyHeading: 'No storage sources yet',
        emptyDescription: 'Add a disk folder or an S3 bucket, then point each file type at it below.',
        create: 'New source',
        edit: 'Edit',
        delete: 'Delete',
        deletePrompt: (name: string) => `Delete the source “${name}”? This only works while no file type uses it.`,
        usedBy: (n: number) => `${n} file type${n === 1 ? '' : 's'}`,
        unused: 'Unused',
        defaultBasePath: './uploads',
        nameLabel: 'Name',
        namePlaceholder: 'Primary uploads',
        typeLabel: 'Type',
        basePathLabel: 'Base path',
        basePathPlaceholder: './uploads',
        basePathHint: 'Folder on this server’s disk. Defaults to ./uploads.',
        bucketLabel: 'Bucket',
        regionLabel: 'Region',
        endpointLabel: 'Custom endpoint',
        endpointHint: 'Only for S3-compatible providers that are not AWS — leave empty for AWS.',
        accessKeyIdLabel: 'Access key ID',
        secretLabel: 'Secret access key',
        secretHint: 'Leave empty to keep the current secret, or to use the server’s default AWS credentials.',
        secretSet: 'A secret is set.',
        sourceSaved: 'Storage source saved.',
        sourceDeleted: 'Storage source deleted.',
        saveFailed: 'Could not save that.',
        bindingsTitle: 'File types',
        bindingsIntro: 'Every file type the application code uploads, and which source it lands on.',
        bindingsSaved: 'Saved.',
        unbound: '— none —',
        bindingsNoSources: 'Create a storage source first — there is nowhere to put these files yet.',
        unassignedWarning: (n: number) =>
            `${n} file type${n === 1 ? ' has' : 's have'} no source. Uploads of ${n === 1 ? 'that type' : 'those types'} are rejected until you assign one.`,
        unassigned: 'Not assigned',
        unsaved: 'Unsaved',
        save: 'Save assignments',
    },

    jobs: {
        tab: 'Scheduled jobs',
        title: 'Schedules',
        intro: 'Recurring work registered in code, and when the scheduler will next pick it up. Schedules are defined alongside their handler — this screen is a read-only view of them.',
        empty: 'No scheduled jobs are registered.',
        colKind: 'Job',
        colCron: 'Schedule',
        colNext: 'Next run',
        colLast: 'Last run',
        runOne: 'Run now',
        runAll: 'Run all now',
        triggered: (n: number) =>
            n === 1 ? 'Queued 1 job to run now.' : `Queued ${n} jobs to run now.`,
        runFailed: 'Could not queue that job.',
        neverRan: 'Never run',
        runsTitle: 'Recent runs',
        runsIntro: 'The last jobs the worker picked up, newest first — including one-off runs triggered from here.',
        runsEmpty: 'No jobs have run yet.',
        loadMore: 'Load more',
        loadedCount: (n: number) => `Showing ${n}`,
        colStatus: 'Status',
        colAttempts: 'Attempts',
        colFinished: 'Finished',
        colError: 'Error',
        filterStatus: 'Status',
        filterAll: 'All',
        passedOf: 'passed of',
        buildWord: 'build',
        buildsWord: 'builds',
        taggedCount: (n: number) => `${n} tagged`,
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Job kind or error',
        statusLabels: {
            queued: 'Queued',
            running: 'Running',
            done: 'Done',
            failed: 'Failed',
            canceled: 'Canceled',
        } as Record<string, string>,
        statsSummary: (queued: number, failed: number) =>
            `${queued} queued · ${failed} failed`,
    },

    retention: {
        tab: 'Data retention',
        title: 'Tables',
        intro: 'Nothing is ever hard-deleted by the app — a delete only stamps “deleted_at”. Set how long each table keeps those rows before the purge worker removes them for good.',
        neverLabel: 'Keep forever',
        neverHint: '0 = keep forever',
        colTable: 'Table',
        colRows: 'Rows',
        colSoftDeleted: 'Soft-deleted',
        colDue: 'Due for purge',
        colDays: 'Keep for (days)',
        save: 'Save retention',
        saved: 'Saved.',
        saveFailed: 'Could not save that.',
        unsaved: 'Unsaved',
        dueNow: (n: number) => `${n} row${n === 1 ? '' : 's'} ready to be purged now.`,
        allClear: 'Nothing is waiting to be purged.',
        settingsTitle: 'Purge worker',
        settingsIntro: 'The worker runs beside the API and deletes in small batches so it never blocks requests. Lower the batch or lengthen the interval if the database is busy.',
        intervalLabel: 'Run every (seconds)',
        intervalHint: 'How often the worker wakes up. Applied on its next run.',
        batchLabel: 'Rows per table, per run',
        batchHint: 'Upper bound on rows deleted from one table in one pass.',
        tablesPerTickLabel: 'Tables per run',
        tablesPerTickHint: 'The worker walks the tables round-robin, so load stays spread out.',
        saveSettings: 'Save worker settings',
        runNow: 'Run once now',
        runFinished: (n: number) => (n === 0 ? 'Purge ran — nothing was due.' : `Purge removed ${n} row${n === 1 ? '' : 's'}.`),
        lastRun: (when: string, n: number) => `Last run ${when} — ${n} row${n === 1 ? '' : 's'} removed.`,
        neverRan: 'The worker has not run since this server started.',
        enabledCount: (n: number) => (n === 0 ? 'No table is set to purge yet.' : `${n} table${n === 1 ? '' : 's'} purging.`),
    },

    devices: {
        title: 'Where you are signed in',
        intro: 'Every browser and device with an active session on your account. Sign out any you do not recognise.',
        currentTitle: 'This device',
        currentBadge: 'Current',
        otherTitle: 'Other devices',
        signOut: 'Sign out',
        emptyTitle: 'No other devices',
        emptyMessage: 'Your account is only active on this device.',
        unknownDevice: 'Unknown device',
        deviceLabel: (browser: string, os: string) => `${browser} on ${os}`,
        lastSeenLabel: 'Last active',
        signedInLabel: 'Signed in',
        ipLabel: 'IP address',
        lastSeen: (when: string) => `Last active ${when}`,
        ip: (value: string) => `IP ${value}`,
    },

    dashboard: {
        greetingMorning: 'Good morning',
        greetingAfternoon: 'Good afternoon',
        greetingEvening: 'Good evening',
        welcomeMessage: 'A few steps to get your workspace going — each one takes you where it happens.',
        stepSignIn: 'Sign in to your workspace',
        stepProfile: 'Set your display name',
        stepProject: 'Create your first project',
        stepTask: 'Upload your first asset',
        goToProjects: 'Open projects',
        statProjects: 'Projects',
        statTasks: 'Assets stored',
        statDueSoon: 'Team members',
        statDueSoonHint: 'People across your projects',
        statUnread: 'Unread notifications',
        recentProjects: 'Recent projects',
        recentActivity: 'Recent activity',
        viewAll: 'View all',
        noProjects: 'No projects yet — create your first one to get started.',
        noActivity: 'Nothing yet. Activity in your projects will show up here.',
        taskCount: (n: number) => (n === 1 ? '1 task' : `${n} tasks`),
        assetCount: (n: number) => `${n} asset${n === 1 ? '' : 's'}`,
        due: (date: string) => `due ${date}`,
    },

    consent: {
        eyebrow: 'One quick step',
        title: 'Before you start',
        body: 'Please review and accept our Privacy Policy and Terms of Service to continue.',
        privacyLink: 'Privacy Policy',
        termsLink: 'Terms of Service',
        agree: 'I have read and accept both documents',
        accept: 'I agree — continue',
    },

    notifications: {
        title: 'Notifications',
        markAllRead: 'Mark all read',
        empty: 'No notifications yet.',
        pushEnable: 'Enable device notifications',
        pushDisable: 'Disable device notifications',
        pushEnabled: 'Device notifications enabled.',
        pushFailed: 'Could not enable device notifications.',
        justNow: 'just now',
        minutesAgo: (n: number) => `${n} min ago`,
        hoursAgo: (n: number) => `${n} h ago`,
        daysAgo: (n: number) => `${n} d ago`,
    },

    alerts: {
        loadFailed: 'Something went wrong while loading.',
        nameSaved: 'Name saved.',
        nameFailed: 'Could not save your name.',
        loginFailed: 'Sign-in failed.',
        consentFailed: 'Could not record your consent.',
        accountExportFailed: 'Could not export your data.',
        accountDeleteFailed: 'Could not delete your account.',
        identityLinked: (provider: string) => `${provider} account connected.`,
        identityLinkFailed: 'Could not connect that account.',
        identityUnlinked: (provider: string) => `${provider} account disconnected.`,
        identityUnlinkFailed: 'Could not disconnect that account.',
        sessionRevoked: 'That device has been signed out.',
        sessionRevokeFailed: 'Could not sign that device out.',
        subscriptionActivated: 'Your plan is active.',
        subscriptionCanceled: 'Subscription canceled.',
        subscriptionCancelFailed: 'Could not cancel the subscription.',
        checkoutUnavailable: 'Checkout is not connected to a payment provider yet — ask an administrator to activate the plan.',
        checkoutFailed: 'Could not start checkout.',
        featureFlagSaved: 'Feature flag saved.',
        featureFlagFailed: 'Could not save that feature flag.',
        emailConfigSaved: 'Email settings saved.',
        emailFailed: 'Could not save that.',
        emailQueued: 'Email queued.',
        emailMessageUpdated: 'Message updated.',
        planSaved: 'Plan saved.',
        planDeleted: 'Plan deleted.',
        planFailed: 'Could not save that plan.',
        invoiceSaved: 'Invoice updated.',
        invoiceFailed: 'Could not update that invoice.',
        enquirySent: 'Thanks — our team will be in touch.',
        enquirySaved: 'Enquiry updated.',
        enquiryFailed: 'Could not send that enquiry.',
        enquiryActionSaved: 'Action recorded.',
    },

    usersAdmin: {
        title: 'Users',
        colName: 'Name',
        colEmail: 'Email',
        colAccess: 'Access',
        colJoined: 'Joined',
        colStatus: 'Status',
        filterSearch: 'Search',
        searchPlaceholder: 'Name or email…',
        filterRole: 'Role',
        filterStatus: 'Status',
        allRoles: 'All roles',
        allStatuses: 'All statuses',
        active: 'Active',
        inactive: 'Inactive',
        activate: 'Activate',
        deactivate: 'Deactivate',
        addUser: 'Add user',
        manageAccess: 'Manage access',
        verifiedBadge: 'Verified',
        activity: 'Activity',
        loginAs: 'Sign in as',
        loginAsConfirm: (who: string) =>
            `You will be signed in as ${who}. The way back is a normal sign-out and sign-in.`,
        loginAsCta: 'Sign in as this user',
        userCreated: 'User created.',
        saved: 'Saved.',
        saveFailed: 'Could not save.',

        createHint: 'The account is claimed when the person first signs in with this email.',
        createEmailLabel: 'Email',
        createEmailPlaceholder: 'person@example.com',
        createNameLabel: 'Name (optional)',
        createRoleLabel: 'Role',
        createSubmit: 'Create user',
    },

    accessAdmin: {
        tab: 'Access & limits',
        limitsHint: 'Quotas: 0 means unlimited. Any other number caps how many a member of this role may own.',

        groups: {
            project: 'Projects',
            task: 'Tasks',
            moderation: 'Moderation',
            audit: 'Audit',
            admin: 'Administration',
            billing: 'Plans & subscriptions',
            invoice: 'Invoices',
            enquiry: 'Sales enquiries',
            email: 'Email',
            file: 'Files',
            signing: 'Token signing',
        } as Record<string, string>,
        rolesTitle: 'Roles',
        bindingsTitle: 'Slots',
        newRole: 'New role',
        bindingsHint: 'Bind each behavioural slot to a role. Sign-up always uses the default slot.',
        unbound: '— none —',
        save: 'Save',
        saved: 'Saved.',
        saveFailed: 'Could not save.',
        roleDeleted: 'Role deleted.',
        reassignPrompt: (name: string) => `This role is still in use. Move those accounts to “${name}” and delete it?`,
        delete: 'Delete role',
        pickRole: 'Pick a role to edit.',
    },

    manageAccess: {
        title: 'Manage access',
        confirmWord: 'OWNER',
        roleLabel: 'Role',
        membersLabel: 'Members',
        variablesTitle: 'Template fields',
        variablesHint: 'Fill the placeholders this template uses.',
        verifiedLabel: 'Verified badge',
        showOverrides: 'Per-account overrides',
        hideOverrides: 'Hide overrides',
        overridesHint: 'Grant or revoke individual permissions and caps for this one account, on top of its role.',
        limitsTitle: 'Limits',
        usage: (used: number, limit: number | null) => `${used}/${limit === null ? '∞' : limit} used`,
        unlimited: 'Unlimited',
        inheritPlaceholder: 'Inherit',
        inherit: 'Reset to inherited',
        permissionsTitle: 'Permissions',
        lastOwner: 'This is the last owner and cannot be demoted or deactivated.',
        clientsWarning: (n: number) => `This account is still linked to ${n} record(s); changing its role leaves them behind.`,
        ownerWarning: 'You are promoting this account to OWNER — full control of the platform. Type OWNER to confirm.',
        confirmPrompt: (word: string) => `Type ${word} to confirm`,
        save: 'Save',
    },

    filters: {
        button: 'Filters',
        buttonWithCount: (n: number) => `Filters (${n})`,
        title: 'Filters',
        apply: 'Apply',
        clear: 'Clear',
    },

    upgrade: {
        cta: 'Upgrade',
        modalTitle: 'Upgrade',
        stamp: 'Upgrade',

        priceAmount: 9,
        howToGet: 'Contact the platform owner to upgrade your account.',
        features: {
            export: {
                title: 'Export projects',
                blurb: 'Download any project and its tasks as JSON.',
                benefits: ['Full project export', 'Machine-readable JSON', 'Back up or migrate your data'],
            },
            unlimitedProjects: {
                title: 'More projects',
                blurb: 'Create as many projects as you need.',
                benefits: ['No project cap', 'Room to organize everything'],
            },
        } as Record<string, { title: string; blurb: string; benefits: string[] }>,
    },

    limits: {
        reachedHint: 'You have reached your limit for this resource.',
    },

    platformSettings: {
        title: 'Platform settings',
        signupsOpenLabel: 'Sign-ups open',
        signupsOpenHint: 'When off, new accounts cannot be created (existing accounts still sign in).',
        salesContactLabel: 'Sales contact',
        salesContactHint: 'Email address or URL shown to accounts that need to contact sales for a manual plan.',
        announcementLabel: 'Announcement',
        announcementHint: 'A short message shown in the app shell. Leave empty to show nothing.',
        save: 'Save',
        saved: 'Settings saved.',
        saveFailed: 'Could not save settings.',
    },

    admin: {
        tabOverview: 'Overview',
        tabUsers: 'Users',
        tabSettings: 'Settings',
        settingsDescription: 'Rename the project, edit its vocabularies, transfer or delete it',
    },

    overview: {
        title: 'Overview',
        signupsTotal: 'Total sign-ups',
        wau: 'Weekly active',
        retention: 'D30 retention',
        projectsTotal: 'Projects',
        buildsTotal: 'Tasks',
        reportQueue: 'Open reports',
        na: 'n/a',
        last30Period: 'vs. 30 days ago',
        signupsChart: 'Sign-ups per week',
        signupsChartSubtitle: 'Last 12 weeks',
        signupsSeries: 'Sign-ups',
        tasksChart: 'Tasks by status',
        projectsChart: 'Projects by visibility',
        rolesChart: 'Accounts by role',
        noData: 'Nothing to chart yet.',
    },

    moderation: {
        title: 'Moderation',
        reportsTitle: 'Open reports',
        auditTitle: 'Audit log',
        reportsEmpty: 'No open reports.',
        auditWhen: 'When',
        auditActor: 'Account',
        auditAction: 'Action',
        auditTarget: 'Target',
        auditDetail: 'Detail',
        auditAll: 'All',
        auditSearchPlaceholder: 'Account, action, target or detail',
        auditFrom: 'From',
        auditTo: 'To',
        auditFilteredByActor: 'Showing activity for one account only.',
        auditEmpty: 'No audit entries yet.',
        resolve: 'Resolve',
        resolved: 'Report resolved.',
        resolvePrompt: 'Resolution note (optional):',
        colTarget: 'Target',
        colReason: 'Reason',
        colReporter: 'Reporter',
        colWhen: 'When',
        colActor: 'Actor',
        colAction: 'Action',
        colDetail: 'Detail',

        reportTitle: 'Report',
        reportCategoriesLabel: 'What kind of problem?',
        reportCategories: [
            { key: 'spam', label: 'Spam' },
            { key: 'abuse', label: 'Abusive' },
            { key: 'inappropriate', label: 'Inappropriate' },
            { key: 'other', label: 'Other' },
        ],
        reportReasonLabel: 'Why are you reporting this?',
        reportReasonPlaceholder: 'Describe the problem…',
        reportSubmit: 'Submit report',
        reportSent: 'Report submitted.',
        reportFailed: 'Could not submit the report.',
    },

    projects: {
        title: 'Projects',
        switcherLabel: 'Project',
        switcherPlaceholder: 'Pick a project',
        switcherSearch: 'Search projects…',
        createNew: 'Create new project',
        createNewHint: 'Start a new game workspace',
        onboardingTitle: 'Create your first project',
        onboardingIntro: 'A project is the workspace for one game — its assets, bundles, builds and configs all live inside it.',
        onboardingNoPermission: 'Your plan does not include creating projects. Ask a teammate to invite you to theirs.',
        wizardTitle: 'Create a project',
        stepProject: 'Project',
        stepProjectHint: 'Choose a name that captures the essence of your project. You can always change it later!',
        stepConfiguration: 'Configuration',
        stepConfigurationHint: 'Categories, tags and build tags',
        stepReview: 'Review',
        stepReviewHint: 'Check and create',
        appTypeLabel: 'Application type',
        appTypeGame: 'Game',
        appTypeApp: 'App',
        appTypePrototype: 'Prototype',
        categoriesLabel: 'Asset categories',
        categoriesHint: 'At least one category is required — assets are filed under these.',
        tagsLabel: 'Asset tags',
        tagsHint: 'Tags are how bundles select files later.',
        buildTagsLabel: 'Build tags',
        buildTagsHint: 'Publish channels, for example production or beta.',
        archive: 'Archive',
        unarchive: 'Restore',
        archived: 'Archived',
        archivedBanner: 'This project is archived and read-only. Restore it to make changes.',
        lockedBanner: 'This project is being moved between realms. It is temporarily locked and read-only — changes are disabled until the move completes.',
        transfer: 'Transfer ownership',
        transferHint: 'The new owner takes over the project quota and storage. You keep no access.',
        transferSearchHint: 'Enter at least 2 characters to search.',
        leave: 'Leave project',
        leaveConfirm: (name: string) => `Leave "${name}"? You will lose access until you are invited again.`,
        typeToConfirm: (name: string) => `Type ${name} to confirm.`,
        vocabulariesSaved: 'Vocabularies saved.',
        realmLabel: 'Build realm',
        ownerLabel: 'Owner',
        memberCount: (n: number) => `${n} member${n === 1 ? '' : 's'}`,
        assetCount: (n: number) => `${n} asset${n === 1 ? '' : 's'}`,
        empty: 'No projects yet. Create your first one.',
        newProject: 'New project',
        nameLabel: 'Name',
        namePlaceholder: 'Project name',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'What is this project about?',
        visibilityLabel: 'Visibility',
        visibilityPrivate: 'Private',
        visibilityShared: 'Shared',
        create: 'Create project',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        deleteConfirm: (name: string) => `Delete "${name}" and all its tasks?`,
        export: 'Export',
        open: 'Open',
        sharedBadge: 'Shared',
        privateBadge: 'Private',
        noDescription: 'No description.',
        tasksTitle: 'Tasks',
        addTask: 'Add task',
        titleLabel: 'Title',
        taskPlaceholder: 'Task title',
        taskCount: (n: number) => `${n} task${n === 1 ? '' : 's'}`,
        statusLabel: 'Column',
        statusPlanned: 'Planned',
        statusInProgress: 'In progress',
        statusShipped: 'Shipped',
        taskSelected: (title: string) => `Selected: ${title}`,
        noTaskSelected: 'Pick a task to move or delete it.',
        deleteTask: 'Delete task',
        moveBack: 'Move back',
        moveForward: 'Move forward',
        deleteTaskConfirm: (title: string) => `Delete "${title}"?`,
        created: 'Project created.',
        saved: 'Project saved.',
        deleted: 'Project deleted.',
        saveFailed: 'Could not save the project.',
        exportFailed: 'Could not export the project.',

        updatedAt: (date: string) => `Updated ${date}`,
        statMembersTitle: 'Members',
        statMembersDesc: 'People with access',
        statAssetsTitle: 'Assets',
        statAssetsDesc: 'Files ready to bundle',
        statAgeTitle: 'Project age',
        statAgeDesc: 'Days since created',
        statVisibilityTitle: 'Visibility',
        statVisibilitySharedDesc: 'Visible to the team',
        statVisibilityPrivateDesc: 'Visible only to you',

        tabRoadmap: 'Roadmap',
        tabSettings: 'Settings',
        settingsDescription: 'Rename the project, edit its vocabularies, transfer or delete it',
        dangerZone: 'Danger zone',
        deleteProjectHint: 'Deleting a project removes all of its tasks. This cannot be undone.',

        iconLabel: 'Icon',
        colorLabel: 'Color',
        priorityLabel: 'Priority',
        priorityHint: 'How urgent this project is, 1–5. Used only for your own ordering.',
        dueDateLabel: 'Due date',
        notifyLabel: 'Notify me on activity',
        notifyHelp: 'Get an in-app notification when a task in this project changes.',
    },

    pipeline: {
        label: 'Project pipeline',
        assets: 'Assets',
        bundles: 'Bundles',
        builds: 'Builds',
        live: 'Live',
    },

    members: {
        title: 'Members',
        pageDescription: 'Invite teammates and manage what they can do',
        memberWord: 'member',
        membersWord: 'members',
        tabMembers: (n: number) => `Members (${n})`,
        tabInvites: (n: number) => `Invites (${n})`,
        invite: 'Invite',
        inviteTitle: 'Invite someone',
        inviteEmailLabel: 'Email address',
        inviteUsernameLabel: 'Account name',
        invitePermissionsLabel: 'What can they do?',
        inviteReadOnlyHint: 'With no permissions selected they can read everything and change nothing.',
        inviteSent: 'Invitation sent.',
        editPermissions: 'Edit permissions',
        remove: 'Remove',
        removeConfirm: (name: string) => `Remove ${name} from this project?`,
        removeNamed: (name: string) => `Remove ${name}`,
        removeCaption: 'Remove from project',
        revoke: 'Revoke',
        owner: 'Owner',
        emptyRoster: 'No members yet.',
        emptyInvites: 'No pending invitations.',
        pendingSince: (date: string) => `Invited ${date}`,
        expires: (date: string) => `Expires ${date}`,
        singleSeatPlan: 'Your plan is single-seat — upgrade to invite teammates.',
        myInvites: 'Your invitations',
        accept: 'Accept',
        decline: 'Decline',
    },

    realms: {
        title: 'Realms',
        empty: 'No realms yet. Add the first build machine.',
        add: 'Add realm',
        edit: 'Edit realm',
        nameLabel: 'Name',
        baseUrlLabel: 'Base URL',
        regionLabel: 'Region',
        planLabel: 'Plan tier',
        anyPlan: 'Any plan',
        exclusiveLabel: 'Exclusive',
        exclusiveHint: 'Exclusive realms only receive projects by an explicit move.',
        statusLabel: 'Status',
        statusActive: 'Active',
        statusDraining: 'Draining',
        statusOffline: 'Offline',
        healthLabel: 'Health',
        diskFree: 'Disk free',
        queueDepth: 'Queue depth',
        projectCount: 'Projects',
        lastSeen: 'Last seen',
        never: 'Never',
        rotateToken: 'Rotate token',
        tokenTitle: 'Realm token',
        tokenHint: 'Copy this now — it is shown once and cannot be recovered.',
        deleteTitle: 'Delete realm',
        deleteBlocked: (count: number) => `${count} project(s) still live on this realm. Move them first.`,
        moveTitle: 'Move project',
        moveHint: 'The project is locked until the transfer completes.',
        moveStarted: 'The move has started. The project is locked until it finishes.',
        saveFailed: 'Could not save the realm.',
    },

    usage: {
        title: 'Usage',
        storage: 'Storage',
        projects: 'Projects',
        members: 'Members',
        bundles: 'Bundles',
        configs: 'Configs',
        graceZone: 'You are over your storage limit. Uploads still work for now — free space or upgrade.',
        blocked: 'You are far over your storage limit. Uploads are blocked until you free space or upgrade.',
        planLimitTitle: 'Plan limit reached',
        planLimitBody: (resource: string, used: string, limit: string, plan: string) =>
            `You have reached the limit for ${resource} on your ${plan} plan. Current usage: ${used} / ${limit}.`,
        dismiss: 'Dismiss',
        viewSubscription: 'View subscription',
    },

    assets: {
        title: 'Assets',
        pageDescription: 'Upload and organize your project assets',
        empty: 'No assets yet. Drop files here to get started.',
        queueTitle: 'Upload Queue',
        uncategorized: 'Uncategorized',
        emptyTitle: 'No assets yet',
        emptyBody: 'Drop art, audio or data files below. Tag them once and every bundle that matches those tags picks them up automatically.',
        countLine: (files: number, size: string) => `${files} file${files === 1 ? '' : 's'} · ${size}`,
        upload: 'Upload files',
        fileWord: 'file',
        filesWord: 'files',
        stored: 'stored',
        defaultCategoryHint: (name: string) => `New files land in ${name}. Change the default in project settings.`,
        save: 'Save',
        discard: 'Discard',
        delete: 'Delete',
        tagsLabel: 'Tags',
        tagsHint: 'Bundles select files by tag. Add one here and every matching bundle picks this file up.',
        editTags: 'Edit tags',
        rejected: (names: string) => `These files were not accepted: ${names}`,
    },

    bundles: {
        title: 'Bundles',
        pageDescription: 'Manage your project bundles',
        subline: 'selecting files by tag',
        ruleWord: 'rule',
        rulesWord: 'rules',
        intro: 'A bundle is a saved rule for selecting files. Re-tag a file and its bundles follow.',
        emptyTitle: 'No bundles yet',
        empty: 'A bundle is a saved tag rule. Create one and every matching asset is packed into its builds — re-tag a file later and the bundle follows.',
        create: 'New bundle',
        edit: 'Edit bundle',
        runBuild: 'Run build',
        deleteNamed: (name: string) => `Delete ${name}`,
        editNamed: (name: string) => `Edit ${name}`,
        assetCount: (n: number) => `${n} file${n === 1 ? '' : 's'} matched`,
        nameLabel: 'Name',
        engineLabel: 'Engine',
        categoryLabel: 'Category',
        includedLabel: 'Included tags',
        excludedLabel: 'Excluded tags',
        buildTagLabel: 'Build tag',
        algorithmLabel: 'Packing algorithm',
        downscaleLabel: 'Downscale (%)',
        rotationLabel: 'Allow rotation',
        previewTitle: 'Preview',
        previewEmpty: 'No files match the current query. Adjust the category or tags.',
        previewCount: (n: number) => `${n} file${n === 1 ? '' : 's'} matched your query.`,
        deleteWarning: 'All builds associated with this bundle will also be deleted.',
    },

    builds: {
        title: 'Builds',
        pageDescription: 'Manage your project builds',
        emptyTitle: 'No builds yet',
        empty: 'Run a build from a bundle and the packed output shows up here, ready to tag.',
        emptyFilteredTitle: 'Nothing matches that filter',
        purge: 'Purge untagged',
        purgeCount: (n: number) => `Purge ${n} untagged`,
        purged: (n: number) => `${n} untagged build(s) removed.`,
        delete: 'Delete',
        untagged: 'untagged',
        tagPlaceholder: 'Move a build tag to the latest passed build',
        details: 'Details',
        deleteNamed: (bundle: string, hash: string) => `Delete ${bundle} · ${hash}`,
        integrateTitle: 'How to integrate',
        integrateIntro: 'Use these identifiers and the snippet below to load this build in your game.',
        identifiers: 'Identifiers',
        copy: 'Copy',
        copied: 'Copied',
        manageTag: 'Add / Remove tag',
        groupedHint: 'Grouped by bundle. Tagging a build protects it from Purge untagged.',
        filterAll: 'All',
        passedOf: 'passed of',
        buildWord: 'build',
        buildsWord: 'builds',
        taggedCount: (n: number) => `${n} tagged`,
        buildNow: 'Build now',
        buildCount: (n: number) => `${n} builds`,
        showAll: (n: number) => `Show all (${n} builds)`,
        emptyFiltered: 'Clear the filter to see the rest of this project\u2019s builds.',
        closeDetails: 'Close',
        projectIdLabel: 'Project ID',
        buildTagPreferred: 'Build tag (preferred)',
        buildIdLabel: 'Build ID',
        snippetLabel: 'Load the manifest',
        hashLabel: 'Hash',
        sizeLabel: 'Size',
        durationLabel: 'Duration',
        tagLabel: 'Tag',
        status: {
            queued: 'Queued',
            running: 'Running',
            pass: 'Passed',
            fail: 'Failed',
        } as Record<string, string>,
    },

    configs: {
        title: 'Configs',
        pageDescription: 'Manage your project configs',
        configWord: 'config',
        configsWord: 'configs',
        schemaWord: 'schema',
        schemasWord: 'schemas',
        tabConfigs: 'Configs',
        tabSchemas: 'Schemas',
        createConfig: 'New config',
        createSchema: 'New schema',
        needSchema: 'Create a schema first — a config needs a shape to validate against.',
        emptyConfigs: 'No configs yet.',
        emptySchemas: 'No schemas created yet.',
        emptySchemasHint: 'Use the Add button to create your first schema.',
        schemaNameHelper: 'Unique name for the schema',
        defaultTab: 'Default',
        updateSchema: 'Update schema',
        versionCount: 'versions',
        usedBy: (n: number) => `Used by ${n} config(s)`,
        open: 'Open',
        deleteNamed: (key: string) => `Delete ${key}`,
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        keyLabel: 'Key',
        schemaLabel: 'Schema',
        descriptionLabel: 'Description',
        nameLabel: 'Name',
    },

    modal: {
        cancel: 'Cancel',
        back: 'Back',
        next: 'Next',
        save: 'Save',
        apiKeyTitle: 'New API key',
        webhookTitle: 'Webhook endpoint',
        assetSourceTitle: 'Storage source',
        createUserTitle: 'Add user',
        deleteAccountTitle: 'Delete account',
        deleteAccountBody: 'This permanently removes your account and everything you own.',
        deleteAccountHint: (word: string) => `Type ${word} to confirm.`,
        confirmDeleteAccount: 'Delete my account',
        createProjectTitle: 'New project',
        editAssetTagsTitle: 'Edit tags',
        createTaskTitle: 'New task',
        deleteTaskTitle: 'Delete task',
        deleteProjectTitle: 'Delete project',
        reportTitle: 'Report',
        resolveReportTitle: 'Resolve report',
        contactSalesTitle: 'Contact sales',
        planEditorTitle: 'Plan',
        upgradeTitle: 'Upgrade',
        manageAccessTitle: 'Manage access',
        impersonateTitle: 'Sign in as user',
        filtersTitle: 'Filters',
        signingPublicKeyTitle: 'Public key',
        rotateSigningKeyTitle: 'Rotate signing key',
    },
} as const

export type AppStrings = typeof STRINGS
