import { ApiErrorCode, RESOURCE_LABELS } from '@appkit/api/contracts'

const ERROR_MESSAGES = {
    unauthorized: 'Sign in to continue.',
    forbidden: 'You do not have permission to do that.',
    not_found: 'That could not be found.',
    conflict: 'That change conflicts with the current state — refresh and try again.',
    invalid_input: 'Some of the entered values are invalid.',
    unavailable: 'The service is temporarily unavailable. Try again shortly.',
    request_failed: 'The request failed. Please try again.',
    internal_error: 'Something went wrong on our side. Please try again.',
    cross_origin_rejected: 'The request was blocked for security reasons.',
    invalid_body: (field = 'a field') => `Invalid value for “${field}”.`,
    user_not_found: (id = '') => (id ? `Account “${id}” could not be found.` : 'That account could not be found.'),
    name_required: 'A name is required.',
    email_exists: 'A user with that email already exists.',
    account_deactivated: 'This account is deactivated.',
    owner_cannot_self_delete: 'The owner account cannot delete itself — hand the owner role over first.',
    self_impersonation: 'You are already signed in as this account.',
    self_role_change: 'You cannot change your own role or deactivate yourself.',
    self_access_change: 'You cannot change your own permissions or limits.',
    last_owner: 'The last owner cannot be demoted or deactivated.',
    sso_not_configured: 'This sign-in provider is not configured on this server.',
    dev_login_disabled: 'Developer login is disabled.',
    identity_not_found: 'That sign-in method is not connected to your account.',
    identity_linked_elsewhere: 'That account is already connected to a different user.',
    last_identity: 'You cannot disconnect your only sign-in method.',
    session_not_found: 'That session has already ended.',
    current_session: 'This is the device you are using — sign out from the menu instead.',
    target_not_found: 'The reported content could not be found.',
    report_exists: 'You already have an open report for this.',
    report_not_found: 'That report could not be found.',
    report_not_pending: 'This report has already been resolved.',
    invalid_push_endpoint: 'That push subscription is invalid.',
    id_required: 'A valid identifier is required.',
    role_not_found: (id = '') => (id ? `Role “${id}” could not be found.` : 'That role could not be found.'),
    role_exists: 'A role with that identifier already exists.',
    role_reserved: 'That identifier is reserved.',
    role_builtin: 'The reserved role cannot be changed.',
    role_in_use: (count = 'some') => `${count} account(s) still hold this role.`,
    role_bound: 'This role is bound to a slot in settings — unbind it first.',
    default_role_required: 'A default role must be set.',
    feature_disabled: 'That feature is not enabled on this workspace.',
    plan_exists: 'A plan with that name already exists.',
    plan_in_use: (plan = '', count = '') => `${count} account(s) are still subscribed to “${plan}”.`,
    plan_name_required: 'A plan name is required.',
    plan_role_required: 'Pick the role this plan grants.',
    answers_required: (field = 'A field') => `${field} is required.`,
    enquiry_not_found: 'That enquiry could not be found.',
    enquiry_exists: 'You already have an open sales enquiry — we will come back to you before you can send another.',
    invoice_not_found: 'That invoice could not be found.',
    template_not_found: 'That email template could not be found.',
    template_exists: 'A template with that name already exists.',
    template_required: 'A name, subject and body are required.',
    trigger_not_found: 'That trigger could not be found.',
    message_not_found: 'That message could not be found.',
    recipients_required: 'No recipients matched this audience.',
    email_not_configured: 'Set a sender address before sending mail.',
    plan_not_found: 'That plan is no longer available.',
    billing_unavailable: 'Billing is not connected to a payment provider yet.',
    already_subscribed: 'You are already on this plan.',
    not_subscribed: 'There is no active subscription to cancel.',
    limit_reached: (resource = '', limit = '') =>
        `You have reached the limit of ${limit} ${(RESOURCE_LABELS[resource as keyof typeof RESOURCE_LABELS] ?? resource).toLowerCase()}.`,
    project_not_found: 'That project could not be found.',
    task_not_found: 'That task could not be found.',
    title_required: 'A title is required.',
    rate_limited: (retry = '') =>
        retry ? `Too many attempts — try again in ${retry} seconds.` : 'Too many attempts — try again shortly.',
    email_invalid: 'Enter a valid email address.',
    magic_link_invalid: 'That sign-in link has expired or was already used. Request a new one.',
    api_key_not_found: 'That API key could not be found.',
    api_key_name_required: 'Give the key a name.',
    coupon_code_required: 'A coupon code is required.',
    coupon_value_required: 'Set a percentage or a fixed amount.',
    coupon_not_found: 'That coupon is not valid.',
    coupon_already_redeemed: 'You have already used this coupon.',
    job_not_found: 'That job could not be found.',
    job_kind_unknown: (kind = '') =>
        kind ? `No handler is registered for the job “${kind}”.` : 'No handler is registered for that job.',
    webhook_not_found: 'That webhook could not be found.',
    webhook_url_invalid: 'Enter a valid http(s) URL.',
    file_source_not_found: 'That storage source could not be found.',
    file_source_name_required: 'Give the source a name.',
    file_source_config_invalid: 'Check the source configuration — a bucket is required for S3 sources.',
    file_source_in_use: 'Reassign every file type using this source, and remove any files stored on it, first.',
    file_not_found: 'That file could not be found.',
    file_type_invalid: 'Unknown file type.',
    file_type_unassigned: 'No storage source is configured for this file type yet.',
    signing_key_not_found: 'Unknown signing key.',
    signing_key_unavailable: 'The signing key could not be read. Check the key directory on the server.',
    fallback: 'Something went wrong. Please try again.',
} satisfies Record<ApiErrorCode | 'fallback', string | ((...params: string[]) => string)>

export const STRINGS = {
    errors: ERROR_MESSAGES,
    common: {
        loadFailed: 'Something went wrong while loading.',
        noResults: 'No results',
        retry: 'Try again',
        search: 'Search',
        selectMultiple: 'Select one or more…',
        legalBack: 'Back',
        legalUpdated: (date: string) => `Last updated ${date}`,
    },

    commandPalette: {
        hint: 'Search',
        hintTitle: 'Search projects and jump anywhere',
        placeholder: 'Jump to a project, or type a command…',
        groupGo: 'Go to',
        groupProjects: 'Projects',
        groupActions: 'Actions',
        newProject: 'New project',
        newTask: (project: string) => `New task in “${project}”`,
        openProjects: 'Projects',
        openDashboard: 'Dashboard',
        openProfile: 'Profile',
        openAdmin: 'Administration',
        openModeration: 'Moderation',
        openBilling: 'Billing',
        openInvoices: 'Invoices',
        openEnquiries: 'Sales enquiries',
        openEmail: 'Email',
        taskCount: (n: number) => (n === 1 ? '1 task' : `${n} tasks`),
    },

    network: {
        offlineTitle: 'You are offline',
        offlineBody: 'Changes you make now will not be saved until the connection comes back.',
        backOnline: 'Back online.',
        unreachable: 'Could not reach the server. Check your connection and try again.',
    },

    crash: {
        title: 'This page hit an error',
        body: 'The rest of the app is still running — go back, or reload if it keeps happening.',
        reload: 'Reload the page',
        back: 'Go back',
        detailsLabel: 'Technical details',
        copy: 'Copy details',
        copied: 'Copied.',
    },

    validation: {
        invalid: 'This value is not valid.',
        required: 'This field is required.',
        tooLong: (max: number) => `Must be at most ${max} characters.`,
    },

    nav: {
        dashboard: 'Dashboard',
        projects: 'Projects',
        profile: 'Profile',
        billing: 'Billing',
        admin: 'Admin',
        moderation: 'Moderation',
        sectionMain: 'Workspace',
        sectionPlatform: 'Platform',
        invoices: 'Invoices',
        enquiries: 'Sales enquiries',
        email: 'Email',
    },

    pages: {
        landingTitle: 'AppKit — ship your product, not your scaffolding',
        landingDescription: 'A Postgres-backed Fastify API and a React 19 SPA, wired together and ready to build on.',
        dashboardTitle: 'Dashboard',
        dashboardDescription: 'Your workspace at a glance.',
        projectsTitle: 'Projects',
        projectsDescription: 'Create and organize your projects and tasks.',
        projectDetailTitle: 'Project',
        projectDetailDescription: 'Project details and tasks.',
        profileTitle: 'Profile',
        profileDescription: 'Your account details, data export and deletion.',
        adminTitle: 'Administration',
        adminDescription: 'Users, access policy and platform settings.',
        invoicesTitle: 'Invoices',
        invoicesDescription: 'Invoices issued to accounts on this workspace.',
        billingTitle: 'Billing',
        billingDescription: 'Your plan, invoices and upgrades.',
        emailTitle: 'Email',
        emailDescription: 'Templates, triggers and the outbox.',
        enquiriesTitle: 'Sales enquiries',
        enquiriesDescription: 'Plan applications waiting for a sales follow-up.',
        publicInvoiceTitle: 'Invoice',
        publicInvoiceDescription: 'Printable invoice.',
        moderationTitle: 'Moderation',
        moderationDescription: 'Reports queue and the audit log.',
        privacyTitle: 'Privacy Policy',
        termsTitle: 'Terms of Service',
        loginTitle: 'Sign in',
    },

    landing: {
        eyebrow: 'Open starter template',
        heroTitle: 'Ship your product, not your scaffolding',
        heroDescription:
            'AppKit is a Postgres-backed Fastify API and a React 19 SPA with the unglamorous parts already built: sessions, roles, quotas, notifications, moderation — and one worked feature to copy.',
        heroNote: 'MIT-licensed. Clone it, gut it, ship it.',
        ctaPrimary: 'Start building',
        ctaSecondary: 'See what ships',
        ctaDashboard: 'Open dashboard',

        metricPermissions: 'permission keys',
        metricRoles: 'seeded roles',
        metricCommands: 'commands to running',
        terminal: [
            { type: 'command', text: 'npm install' },
            { type: 'command', text: 'npm run migrate' },
            { type: 'output', text: 'goose: applied 00001_schema.sql, 00002_seed.sql' },
            { type: 'command', text: 'npm run dev' },
            { type: 'output', text: 'api listening on :5000 · web on :5001' },
            { type: 'output', text: 'first sign-in becomes the owner — you are live' },
        ],
        pricingTitle: 'Plans',
        pricingIntro: 'What this workspace sells today.',
        pricingContact: 'Contact sales',
        pricingStart: 'Get started',
        featuresTitle: 'Everything a product needs on day one',
        featuresIntro: 'Not a UI kit and not a framework — a running application you take over.',
        features: [
            { icon: 'KeyRound', eyebrow: 'Auth', title: 'Sessions & SSO', description: 'Opaque cookie sessions, Google SSO, a dev-only email login. The first account becomes the owner.' },
            { icon: 'ToggleRight', eyebrow: 'Access', title: 'Roles as data', description: 'Roles are database rows edited at runtime — permissions, per-account overrides, quotas and a paywall.' },
            { icon: 'Bell', eyebrow: 'Engage', title: 'Notifications', description: 'An in-app inbox plus web push, delivered through one service layer.' },
            { icon: 'Flag', eyebrow: 'Trust', title: 'Moderation & audit', description: 'A reports queue and an append-only audit log of every administrative action.' },
            { icon: 'Users', eyebrow: 'Admin', title: 'User management', description: 'A directory with create, deactivate and impersonate — plus self-serve export and deletion.' },
            { icon: 'FolderKanban', eyebrow: 'Copy this', title: 'A worked example', description: 'Projects & Tasks touches every layer end to end. Duplicate it and rename things.' },
        ],
        stackTitle: 'One pattern, every layer',
        stackIntro:
            'Every feature walks the same chain, so the second one is a copy of the first. No ORM, no query builder — SQL you can read.',
        stack: [
            { title: 'Contract', description: 'api/src/contracts — one shared type both sides import' },
            { title: 'Router', description: 'Fastify plugin with inline JSON Schema validation' },
            { title: 'Service', description: 'capability checks, quotas, business rules' },
            { title: 'Repository', description: 'raw pg, SQL in .sql files' },
            { title: 'SPA', description: 'slice → service → module — one zustand store' },
        ],

        stackChain: [
            'api/src/contracts/projects.ts        # the shared type',
            'api/src/routers/projectRouter.ts     # validation + ownership checks',
            'api/src/services/ProjectService.ts   # capability + quota gating',
            'api/src/db/repositories/projects/    # raw SQL, one verb per file',
            'web/src/state/projects.slice.ts      # the same contract, client side',
        ].join('\n'),
        quickStartTitle: 'Running in three commands',
        quickStartIntro: 'A fresh clone to a signed-in owner account in under two minutes.',
        quickStart: [
            { title: 'Install', description: 'One npm workspace: api, web and migrations together.', code: 'npm install' },
            { title: 'Migrate', description: 'Creates the database and applies the schema and seed.', code: 'npm run migrate' },
            { title: 'Run', description: 'API on :5000, web on :5001. Sign in — you are the owner.', code: 'npm run dev' },
        ],
        faqTitle: 'The questions you would ask',
        faq: [
            { question: 'Is this a framework?', answer: 'No. It is an application you take over — delete the example feature, keep the plumbing, and everything stays plain Fastify, React and SQL.' },
            { question: 'Why no ORM?', answer: 'Raw pg with SQL in .sql files reads exactly as it runs. The repository layer keeps queries in one place; the compiler keeps the row types honest.' },
            { question: 'How do roles work?', answer: 'Roles are rows created at runtime. Each grants permission keys; per-account overrides and quotas layer on top. Nothing is hardcoded except the owner.' },
            { question: 'What about deployment?', answer: 'One Docker image runs migrations and the API; the web build deploys anywhere static. A single CORS_ORIGIN switch flips between same-origin and split hosting.' },
        ],
        footerTagline: 'A starter you can ship',
        footerDescription: 'Auth, roles, notifications and a worked example feature — ready to build on.',
        footerCtaHeading: 'Start where the plumbing ends',
        footerCtaDescription: 'Sign in and poke around the running product.',
        footerCta: 'Open the app',
        footerProduct: 'Product',
        footerSignIn: 'Sign in',
        footerDashboard: 'Dashboard',
        footerLegal: 'Legal',
        legalText: 'MIT licensed.',
    },

    auth: {
        title: 'Sign in',
        subtitle: 'Sign in to your account.',
        heroEyebrow: 'Starter Template',
        heroTitle: 'A React + Fastify starter you can ship',
        heroSubtitle:
            'Authentication, user management, roles & feature flags, notifications and a worked example feature — ready to build on.',
        signInWith: (provider: string) => `Continue with ${provider}`,
        loginAsOwner: 'Log in as owner',
        devTitle: 'Developer sign-in',
        devHint: 'Email-only sign-in for local development. The first account ever created becomes the owner.',
        emailPlaceholder: 'you@example.com',
        namePlaceholder: 'Display name (optional)',
        signIn: 'Sign in',
        signOut: 'Sign out',
        ssoFailed: 'Sign-in failed. Please try again.',
        ssoDeactivated: 'This account has been deactivated.',
        footerTagline: 'Built on the app starter template.',
        ecosystem: {
            title: 'Everything already wired in',
            coreName: 'AppKit',
            coreLabel: 'starter',
            rings: [
                {
                    label: 'Platform',
                    items: [
                        { name: 'Auth & SSO' },
                        { name: 'Roles & flags' },
                        { name: 'User admin' },
                    ],
                },
                {
                    label: 'Product',
                    items: [
                        { name: 'Projects & Tasks' },
                        { name: 'Notifications' },
                        { name: 'Paywall & quotas' },
                        { name: 'Moderation' },
                        { name: 'Audit log' },
                    ],
                },
            ],
        },
    },

    account: {
        legalTitle: 'Legal',
        legalPrivacy: 'Privacy Policy',
        legalTerms: 'Terms of Service',
        exportTitle: 'Export your data',
        exportDescription: 'Download everything you own as a JSON file.',
        exportAction: 'Export data',
        deleteTitle: 'Delete account',
        deleteDescription: 'Permanently remove your account and everything you own. This cannot be undone.',
        deleteAction: 'Delete account',
        deleteOwnerBlocked: 'The owner account cannot be deleted while it holds the owner role. Hand the role over first.',
    },

    profile: {
        title: 'Profile',
        intro: 'Edit your display name, export your data or delete your account — everything else comes from your sign-in provider or is set by an administrator.',
        nameLabel: 'Display name',
        emailLabel: 'Email',
        roleLabel: 'Role',
        membersLabel: 'Members',
        variablesTitle: 'Template fields',
        variablesHint: 'Fill the placeholders this template uses.',
        joinedLabel: 'Joined',
        statusLabel: 'Status',
        statusActive: 'Active',
        statusInactive: 'Deactivated',
        verifiedBadge: 'Verified',
        save: 'Save',
        connectionsTitle: 'Connected accounts',
        connectionsIntro: 'Sign in with any of these — they all open the same account.',
        connectedAs: (email: string) => (email ? `Connected as ${email}` : 'Connected'),
        notConnected: 'Not connected',
        connect: 'Connect',
        disconnect: 'Disconnect',
        lastIdentityHint: 'Your only sign-in method cannot be disconnected.',
        tabAccount: 'Account',
        tabDevices: 'Devices',
    },

    billing: {
        title: 'Subscription',
        intro: 'Your plan and what it unlocks.',
        currentPlanTitle: 'Current plan',
        freePlanName: 'Free',
        freePlanHint: 'The plan every account starts on — no payment required.',
        plansTitle: 'Plans',
        statusLabel: 'Status',
        renewsLabel: 'Renews',
        endsLabel: 'Ends',
        startedLabel: 'Started',
        planLabel: 'Plan',
        subscribe: 'Choose plan',
        currentBadge: 'Current',
        cancel: 'Cancel subscription',
        cancelPending: 'Cancels at period end',
        notConnectedTitle: 'No plans available',
        notConnectedHint: 'No plans are published yet. An administrator creates them in Access & limits.',
        unavailableTitle: 'Upgrades are currently unavailable',
        contactSalesTitle: 'Talk to us to get this plan',
        contactSalesHint: 'This plan is assigned by our team. Get in touch and we will set it up for your account.',
        contactSalesAction: 'Contact sales',
        contactSalesMissing: 'No sales contact has been configured yet — ask an administrator.',
        modeManual: 'Assigned by sales',
        modeManaged: 'Self-serve checkout',
        tabSubscription: 'Subscription',
        tabInvoices: 'Invoices',
        invoicesTitle: 'Your invoices',
        invoicesIntro: 'Every invoice issued to your account.',
        invoicesEmpty: 'No invoices yet.',
        invoicePreview: 'Preview',
        perMonth: '/ month',
        perYear: '/ year',
        freePrice: 'Free',
        currentPlanBadge: 'Your plan',
        enquiryTitle: (plan: string) => `Apply for ${plan}`,
        enquiryIntro: 'Tell us about your needs and our team will set the plan up for your account.',
        enquirySubmit: 'Send application',
        enquiryCancel: 'Cancel',
        enquiryContactHint: (contact: string) => `Prefer email? Write to ${contact}.`,
        statusLabels: {
            none: 'No subscription',
            trialing: 'Trial',
            active: 'Active',
            past_due: 'Past due',
            canceled: 'Canceled',
        },
        price: (amount: string, interval: string) => `${amount} / ${interval}`,
        enquiryPendingAction: 'Request sent',
        enquiryPendingHint: (plan: string, status: string) =>
            `Your request for ${plan} is with our team (${status}). You can send another once it is closed.`,
        enquiryStatusLabels: {
            new: 'received',
            contacted: 'in progress',
            won: 'won',
            lost: 'closed',
        } as Record<string, string>,
        intervalMonth: 'month',
        intervalYear: 'year',
    },

    plansAdmin: {
        title: 'Plans',
        intro: 'Plans a subscription can put an account on. Each plan grants a role — bind it below in Slots.',
        create: 'New plan',
        nameLabel: 'Plan name',
        descriptionLabel: 'Description',
        priceLabel: 'Price (cents)',
        currencyLabel: 'Currency',
        intervalLabel: 'Billing interval',
        modeLabel: 'How it is sold',
        roleLabel: 'Role granted',
        activeLabel: 'Published',
        save: 'Save plan',
        delete: 'Delete plan',
        cancel: 'Cancel',
        empty: 'No plans yet.',
        unpublished: 'Unpublished',
        deletePrompt: (name: string) => `Delete the plan “${name}”?`,
        modeManual: 'Manual — sales assigns it',
        modeManaged: 'Managed — payment gateway',
        modeHint: 'Manual plans collect an application and are assigned by your team. Managed plans check out through the payment gateway.',
        roleHint: 'The role an active subscription on this plan grants.',
        intervalMonth: 'Monthly',
        intervalYear: 'Yearly',
        featuresLabel: 'Features',
        featuresHint: 'One per line — shown on the pricing card.',
        salesFieldsLabel: 'Application fields',
        salesFieldsHint: 'What a manual plan asks for when an account applies.',
        fieldLabelLabel: 'Question',
        fieldLabelPlaceholder: 'e.g. Company',
        fieldTypeLabel: 'Answer type',
        fieldRequiredLabel: 'Required',
        fieldRemove: 'Remove',
        fieldAdd: 'Add field',
        fieldsEmpty: 'No application fields yet — accounts will just send a plain request.',
        fieldTypes: {
            text: 'Short text',
            textarea: 'Long text',
            email: 'Email',
            number: 'Number',
        },
        activeHint: 'Unpublished plans stay hidden from accounts.',
        edit: 'Edit',
        slotLabel: (name: string) => `Plan: ${name}`,
        slotHint: (mode: string) => `The role an active subscription on this plan grants (${mode}).`,
    },

    enquiries: {
        title: 'Sales enquiries',
        intro: 'Applications submitted for plans that sales assigns.',
        columnAccount: 'Account',
        columnPlan: 'Plan',
        columnStatus: 'Status',
        columnDetails: 'Details',
        columnCreated: 'Received',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Name, email or answer',
        filterStatus: 'Status',
        filterPlan: 'Plan',
        filterAll: 'All',
        empty: 'No sales enquiries yet.',
        emptyFiltered: 'No enquiries match these filters.',
        markContacted: 'Contacted',
        markWon: 'Won',
        markLost: 'Lost',
        openTrail: 'Audit trail',
        openAction: 'Add action',
        trailTitle: 'Audit trail',
        trailEmpty: 'Nothing recorded yet.',
        trailKinds: {
            created: 'Application received',
            status: 'Status changed',
            note: 'Note added',
            invoice: 'Invoice created',
        },
        actionTitle: 'Add action',
        actionKindLabel: 'Action',
        actionKindStatus: 'Change status',
        actionKindNote: 'Add a note',
        actionKindInvoice: 'Create an invoice',
        actionStatusLabel: 'New status',
        actionNoteLabel: 'Note',
        actionAmountLabel: 'Amount (cents)',
        actionCurrencyLabel: 'Currency',
        actionAmountHint: 'Leave empty to use the plan price.',
        actionSubmit: 'Record action',
        actionCancel: 'Cancel',
        statusLabels: {
            new: 'New',
            contacted: 'Contacted',
            won: 'Won',
            lost: 'Lost',
        },
    },

    publicInvoice: {
        title: 'Invoice',
        billedTo: 'Billed to',
        issued: 'Issued',
        due: 'Due',
        paid: 'Paid',
        plan: 'Plan',
        amount: 'Amount due',
        status: 'Status',
        print: 'Print',
        notFound: 'This invoice link is not valid.',
        thanks: 'Thank you for your business.',
    },

    invoices: {
        title: 'Invoices',
        intro: 'Every invoice issued on this workspace.',
        columnNumber: 'Invoice',
        columnUser: 'Account',
        columnPlan: 'Plan',
        columnStatus: 'Status',
        columnAmount: 'Amount',
        columnIssued: 'Issued',
        columnProvider: 'Provider',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Number, name or email',
        filterStatus: 'Status',
        filterPlan: 'Plan',
        filterProvider: 'Provider',
        filterFrom: 'Issued from',
        filterTo: 'Issued to',
        filterAll: 'All',
        empty: 'No invoices yet.',
        emptyFiltered: 'No invoices match these filters.',
        markPaid: 'Mark paid',
        markVoid: 'Void',
        view: 'View',
        statusLabels: {
            draft: 'Draft',
            open: 'Open',
            paid: 'Paid',
            void: 'Void',
            uncollectible: 'Uncollectible',
        },
    },

    email: {
        tabOutbox: 'Outbox',
        tabTemplates: 'Templates',
        tabTriggers: 'Triggers',
        tabSettings: 'Delivery',

        settingsTitle: 'Email delivery',
        settingsIntro: 'Where transactional and scheduled mail is sent from.',
        providerLabel: 'Provider',
        providerLog: 'Log only (development)',
        providerSmtp: 'SMTP server',
        providerMailchimp: 'Mailchimp (Mandrill)',
        fromNameLabel: 'Sender name',
        fromEmailLabel: 'Sender address',
        smtpHostLabel: 'SMTP host',
        smtpPortLabel: 'SMTP port',
        smtpUserLabel: 'SMTP username',
        smtpPasswordLabel: 'SMTP password',
        smtpSecureLabel: 'Use TLS (port 465)',
        mailchimpKeyLabel: 'Mandrill API key',
        secretSet: 'Saved — leave blank to keep it.',
        batchSizeLabel: 'Batch size',
        batchSizeHint: 'How many messages the worker sends per tick.',
        save: 'Save',
        sendTest: 'Send test email',
        testQueued: 'Test email queued.',

        outboxTitle: 'Outbox',
        outboxIntro: 'Everything queued, sent or failed on this workspace.',
        outboxEmpty: 'Nothing queued yet.',
        columnTo: 'To',
        columnSubject: 'Subject',
        columnStatus: 'Status',
        columnTemplate: 'Template',
        columnScheduled: 'Scheduled',
        columnAttempts: 'Tries',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Address, subject or body',
        filterStatus: 'Status',
        filterTemplate: 'Template',
        filterAll: 'All',
        retry: 'Retry',
        cancel: 'Cancel',
        statusLabels: {
            queued: 'Queued',
            sending: 'Sending',
            sent: 'Sent',
            failed: 'Failed',
            canceled: 'Canceled',
        },

        composeTitle: 'Compose email',
        compose: 'Compose',
        audienceLabel: 'Audience',
        audienceSelf: 'Just me (test)',
        audienceCustom: 'Specific addresses',
        audienceAllUsers: 'Every active account',
        audienceRole: 'Everyone with a role',
        audienceMembers: 'Selected members',
        roleLabel: 'Role',
        membersLabel: 'Members',
        variablesTitle: 'Template fields',
        variablesHint: 'Fill the placeholders this template uses.',
        emailsLabel: 'Addresses',
        emailsHint: 'Comma separated.',
        templateLabel: 'Template',
        templateNone: 'No template — write it below',
        subjectLabel: 'Subject',
        bodyLabel: 'Body',
        bodyHint: 'Placeholders: {{workspace}}, {{recipientName}}, {{recipientEmail}}, {{date}}.',
        scheduleLabel: 'Send at',
        scheduleHint: 'Leave empty to send on the next worker tick.',
        send: 'Queue email',
        queued: (count: number) => `${count} message${count === 1 ? '' : 's'} queued.`,

        templatesTitle: 'Templates',
        templatesIntro: 'Reusable subjects and bodies for triggers and campaigns.',
        templatesEmpty: 'No templates yet.',
        newTemplate: 'New template',
        editTemplate: 'Edit',
        templateNameLabel: 'Name',
        templateDescriptionLabel: 'Description',
        templateActiveLabel: 'Active',
        templatePreview: 'Preview',
        templateDelete: 'Delete template',
        templateDeletePrompt: (name: string) => `Delete the template “${name}”?`,
        templateSaved: 'Template saved.',

        triggersTitle: 'Audit triggers',
        triggersIntro: 'Send a template whenever an audited action happens.',
        triggersEmpty: 'No triggers yet — every audited action is available.',
        triggerAction: 'Audit action',
        triggerTemplate: 'Template',
        triggerRecipient: 'Send to',
        triggerRecipientActor: 'The account that acted',
        triggerRecipientRole: 'Platform role',
        triggerRecipientMembers: 'Selected members',
        triggerRecipientCustom: 'Fixed addresses',
        triggerRoleLabel: 'Role',
        triggerMembersLabel: 'Members',
        triggerCustomEmail: 'Addresses',
        triggerActive: 'Active',
        triggerAdd: 'Add trigger',
        triggerDelete: 'Delete',
        triggerSaved: 'Trigger saved.',
    },

    featureFlags: {
        title: 'Feature flags',
        intro: 'Turn optional parts of the product on or off for the whole workspace.',
        labels: {
            billing: 'Subscriptions & billing',
            email: 'Email delivery',
            magic_link: 'Magic-link sign-in',
            files: 'File uploads',
        },
        hints: {
            billing: 'Exposes plans, the subscription screen and the billing API. Leave off until a payment provider is connected.',
            email: 'Exposes templates, the outbox and the send worker. Leave off until a provider is configured.',
            magic_link: 'Lets people sign in with a one-time link mailed to them. Needs Email delivery on — the link has no way out otherwise.',
            files: 'Exposes file storage sources and the upload API. Leave off until at least one source is configured.',
        },
        requiresLabel: (flag: string) => `Requires ${flag}`,
    },

    signingKeys: {
        tab: 'Signing keys',
        title: 'Token signing keys',
        intro: 'Key pairs this workspace uses to sign JWTs for other services. The private key never leaves the server — hand the public key to whoever validates the token.',
        empty: 'No signing keys are defined.',
        algorithmLabel: 'Algorithm',
        kidLabel: 'Key ID',
        createdLabel: 'Created',
        publicKeyLabel: 'Public key',
        publicKeyHint: 'Give this to the service that validates tokens signed with this key.',
        showPublicKey: 'Show public key',
        copy: 'Copy',
        copied: 'Copied.',
        close: 'Close',
        rotate: 'Rotate',
        rotateConfirm: 'Rotate key',
        rotatePrompt: (label: string) => `Rotate “${label}”? New tokens use the new key immediately. Tokens already issued stay valid until they expire, so keep the retired public key published until then.`,
        rotated: 'Signing key rotated.',
        rotateFailed: 'Could not rotate the signing key.',
        retired: (count: number) => `${count} retired key${count === 1 ? '' : 's'}`,
        retiredHint: 'Previous public keys are kept so tokens issued before the rotation can still be validated.',
    },

    apiKeys: {
        tab: 'API keys',
        title: 'API keys',
        intro: 'Tokens for scripts and integrations. A key acts as you, limited to the scopes you pick.',
        empty: 'No API keys yet.',
        create: 'New key',
        nameLabel: 'Name',
        namePlaceholder: 'CI deploy bot',
        scopesLabel: 'Scopes',
        scopesHint: 'Leave empty to grant everything the account can do. A scope you do not hold is ignored.',
        expiresLabel: 'Expires',
        expiresHint: 'Leave empty for a key that never expires.',
        revoke: 'Revoke',
        revokePrompt: (name: string) => `Revoke “${name}”? Anything using it stops working immediately.`,
        created: 'API key created.',
        revoked: 'API key revoked.',
        saveFailed: 'Could not save the API key.',
        tokenTitle: 'Copy this key now',
        tokenHint: 'This is the only time the full key is shown. Store it somewhere safe.',
        copy: 'Copy',
        copied: 'Copied.',
        done: 'Done',
        lastUsed: (when: string) => `Last used ${when}`,
        neverUsed: 'Never used',
        expires: (when: string) => `Expires ${when}`,
        neverExpires: 'No expiry',
        scopeCount: (n: number) => (n === 0 ? 'Full account access' : `${n} scope${n === 1 ? '' : 's'}`),
    },

    webhooks: {
        tab: 'Webhooks',
        title: 'Endpoints',
        intro: 'POST every audited action to your own services. Payloads are signed with HMAC-SHA256.',
        empty: 'No endpoints yet.',
        create: 'New endpoint',
        edit: 'Edit',
        delete: 'Delete',
        deletePrompt: (url: string) => `Delete the endpoint “${url}” and its delivery history?`,
        urlLabel: 'Endpoint URL',
        urlPlaceholder: 'https://example.com/hooks/appkit',
        descriptionLabel: 'Description',
        eventsLabel: 'Events',
        eventsHint: 'Audited actions to stream. Leave empty and nothing is sent.',
        activeLabel: 'Active',
        secretLabel: 'Signing secret',
        secretHint: 'Leave empty to keep the current secret. A new one is generated on create.',
        secretSet: 'A signing secret is set.',
        saved: 'Endpoint saved.',
        deleted: 'Endpoint deleted.',
        saveFailed: 'Could not save the endpoint.',
        deliveriesTitle: 'Deliveries',
        deliveriesIntro: 'Every attempt, newest first. Failed deliveries retry with backoff on the job queue.',
        deliveriesEmpty: 'No deliveries yet.',
        columnEndpoint: 'Endpoint',
        columnEvent: 'Event',
        columnStatus: 'Status',
        columnAttempts: 'Attempts',
        columnResponse: 'Response',
        columnCreated: 'Sent',
        filterStatus: 'Status',
        filterAll: 'All',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Event, URL or error',
        statusLabels: {
            pending: 'Pending',
            delivered: 'Delivered',
            failed: 'Failed',
        } as Record<string, string>,
        eventCount: (n: number) => `${n} event${n === 1 ? '' : 's'}`,
        inactive: 'Paused',
    },

    files: {
        tab: 'Files',
        title: 'Storage sources',
        intro: 'Where uploaded files are written. Create as many as you need — different disks, different buckets.',
        empty: 'No storage sources yet.',
        emptyHeading: 'No storage sources yet',
        emptyDescription: 'Add a disk folder or an S3 bucket, then point each file type at it below.',
        create: 'New source',
        edit: 'Edit',
        delete: 'Delete',
        deletePrompt: (name: string) => `Delete the source “${name}”? This only works while no file type uses it.`,
        usedBy: (n: number) => `${n} file type${n === 1 ? '' : 's'}`,
        unused: 'Unused',
        defaultBasePath: './uploads',
        nameLabel: 'Name',
        namePlaceholder: 'Primary uploads',
        typeLabel: 'Type',
        basePathLabel: 'Base path',
        basePathPlaceholder: './uploads',
        basePathHint: 'Folder on this server’s disk. Defaults to ./uploads.',
        bucketLabel: 'Bucket',
        regionLabel: 'Region',
        endpointLabel: 'Custom endpoint',
        endpointHint: 'Only for S3-compatible providers that are not AWS — leave empty for AWS.',
        accessKeyIdLabel: 'Access key ID',
        secretLabel: 'Secret access key',
        secretHint: 'Leave empty to keep the current secret, or to use the server’s default AWS credentials.',
        secretSet: 'A secret is set.',
        sourceSaved: 'Storage source saved.',
        sourceDeleted: 'Storage source deleted.',
        saveFailed: 'Could not save that.',
        bindingsTitle: 'File types',
        bindingsIntro: 'Every file type the application code uploads, and which source it lands on.',
        bindingsSaved: 'Saved.',
        unbound: '— none —',
        bindingsNoSources: 'Create a storage source first — there is nowhere to put these files yet.',
        unassignedWarning: (n: number) =>
            `${n} file type${n === 1 ? ' has' : 's have'} no source. Uploads of ${n === 1 ? 'that type' : 'those types'} are rejected until you assign one.`,
        unassigned: 'Not assigned',
        unsaved: 'Unsaved',
        save: 'Save assignments',
    },

    jobs: {
        tab: 'Scheduled jobs',
        title: 'Schedules',
        intro: 'Recurring work registered in code, and when the scheduler will next pick it up. Schedules are defined alongside their handler — this screen is a read-only view of them.',
        empty: 'No scheduled jobs are registered.',
        colKind: 'Job',
        colCron: 'Schedule',
        colNext: 'Next run',
        colLast: 'Last run',
        runOne: 'Run now',
        runAll: 'Run all now',
        triggered: (n: number) =>
            n === 1 ? 'Queued 1 job to run now.' : `Queued ${n} jobs to run now.`,
        runFailed: 'Could not queue that job.',
        neverRan: 'Never run',
        runsTitle: 'Recent runs',
        runsIntro: 'The last jobs the worker picked up, newest first — including one-off runs triggered from here.',
        runsEmpty: 'No jobs have run yet.',
        loadMore: 'Load more',
        loadedCount: (n: number) => `Showing ${n}`,
        colStatus: 'Status',
        colAttempts: 'Attempts',
        colFinished: 'Finished',
        colError: 'Error',
        filterStatus: 'Status',
        filterAll: 'All',
        filterSearch: 'Search',
        filterSearchPlaceholder: 'Job kind or error',
        statusLabels: {
            queued: 'Queued',
            running: 'Running',
            done: 'Done',
            failed: 'Failed',
            canceled: 'Canceled',
        } as Record<string, string>,
        statsSummary: (queued: number, failed: number) =>
            `${queued} queued · ${failed} failed`,
    },

    retention: {
        tab: 'Data retention',
        title: 'Tables',
        intro: 'Nothing is ever hard-deleted by the app — a delete only stamps “deleted_at”. Set how long each table keeps those rows before the purge worker removes them for good.',
        neverLabel: 'Keep forever',
        neverHint: '0 = keep forever',
        colTable: 'Table',
        colRows: 'Rows',
        colSoftDeleted: 'Soft-deleted',
        colDue: 'Due for purge',
        colDays: 'Keep for (days)',
        save: 'Save retention',
        saved: 'Saved.',
        saveFailed: 'Could not save that.',
        unsaved: 'Unsaved',
        dueNow: (n: number) => `${n} row${n === 1 ? '' : 's'} ready to be purged now.`,
        allClear: 'Nothing is waiting to be purged.',
        settingsTitle: 'Purge worker',
        settingsIntro: 'The worker runs beside the API and deletes in small batches so it never blocks requests. Lower the batch or lengthen the interval if the database is busy.',
        intervalLabel: 'Run every (seconds)',
        intervalHint: 'How often the worker wakes up. Applied on its next run.',
        batchLabel: 'Rows per table, per run',
        batchHint: 'Upper bound on rows deleted from one table in one pass.',
        tablesPerTickLabel: 'Tables per run',
        tablesPerTickHint: 'The worker walks the tables round-robin, so load stays spread out.',
        saveSettings: 'Save worker settings',
        runNow: 'Run once now',
        runFinished: (n: number) => (n === 0 ? 'Purge ran — nothing was due.' : `Purge removed ${n} row${n === 1 ? '' : 's'}.`),
        lastRun: (when: string, n: number) => `Last run ${when} — ${n} row${n === 1 ? '' : 's'} removed.`,
        neverRan: 'The worker has not run since this server started.',
        enabledCount: (n: number) => (n === 0 ? 'No table is set to purge yet.' : `${n} table${n === 1 ? '' : 's'} purging.`),
    },

    devices: {
        title: 'Where you are signed in',
        intro: 'Every browser and device with an active session on your account. Sign out any you do not recognise.',
        currentTitle: 'This device',
        currentBadge: 'Current',
        otherTitle: 'Other devices',
        signOut: 'Sign out',
        emptyTitle: 'No other devices',
        emptyMessage: 'Your account is only active on this device.',
        unknownDevice: 'Unknown device',
        deviceLabel: (browser: string, os: string) => `${browser} on ${os}`,
        lastSeenLabel: 'Last active',
        signedInLabel: 'Signed in',
        ipLabel: 'IP address',
        lastSeen: (when: string) => `Last active ${when}`,
        ip: (value: string) => `IP ${value}`,
    },

    dashboard: {
        greetingMorning: 'Good morning',
        greetingAfternoon: 'Good afternoon',
        greetingEvening: 'Good evening',
        welcomeMessage: 'A few steps to get your workspace going — each one takes you where it happens.',
        stepSignIn: 'Sign in to your workspace',
        stepProfile: 'Set your display name',
        stepProject: 'Create your first project',
        stepTask: 'Track your first task',
        goToProjects: 'Open projects',
        statProjects: 'Projects',
        statTasks: 'Tasks tracked',
        statDueSoon: 'Due soon',
        statDueSoonHint: 'Projects due within 7 days',
        statUnread: 'Unread notifications',
        recentProjects: 'Recent projects',
        recentActivity: 'Recent activity',
        viewAll: 'View all',
        noProjects: 'No projects yet — create your first one to get started.',
        noActivity: 'Nothing yet. Activity in your projects will show up here.',
        taskCount: (n: number) => (n === 1 ? '1 task' : `${n} tasks`),
        due: (date: string) => `due ${date}`,
    },

    consent: {
        eyebrow: 'One quick step',
        title: 'Before you start',
        body: 'Please review and accept our Privacy Policy and Terms of Service to continue.',
        privacyLink: 'Privacy Policy',
        termsLink: 'Terms of Service',
        agree: 'I have read and accept both documents',
        accept: 'I agree — continue',
    },

    notifications: {
        title: 'Notifications',
        markAllRead: 'Mark all read',
        empty: 'No notifications yet.',
        pushEnable: 'Enable device notifications',
        pushDisable: 'Disable device notifications',
        pushEnabled: 'Device notifications enabled.',
        pushFailed: 'Could not enable device notifications.',
        justNow: 'just now',
        minutesAgo: (n: number) => `${n} min ago`,
        hoursAgo: (n: number) => `${n} h ago`,
    },

    alerts: {
        loadFailed: 'Something went wrong while loading.',
        nameSaved: 'Name saved.',
        nameFailed: 'Could not save your name.',
        loginFailed: 'Sign-in failed.',
        consentFailed: 'Could not record your consent.',
        accountExportFailed: 'Could not export your data.',
        accountDeleteFailed: 'Could not delete your account.',
        identityLinked: (provider: string) => `${provider} account connected.`,
        identityLinkFailed: 'Could not connect that account.',
        identityUnlinked: (provider: string) => `${provider} account disconnected.`,
        identityUnlinkFailed: 'Could not disconnect that account.',
        sessionRevoked: 'That device has been signed out.',
        sessionRevokeFailed: 'Could not sign that device out.',
        subscriptionActivated: 'Your plan is active.',
        subscriptionCanceled: 'Subscription canceled.',
        subscriptionCancelFailed: 'Could not cancel the subscription.',
        checkoutUnavailable: 'Checkout is not connected to a payment provider yet — ask an administrator to activate the plan.',
        checkoutFailed: 'Could not start checkout.',
        featureFlagSaved: 'Feature flag saved.',
        featureFlagFailed: 'Could not save that feature flag.',
        emailConfigSaved: 'Email settings saved.',
        emailFailed: 'Could not save that.',
        emailQueued: 'Email queued.',
        emailMessageUpdated: 'Message updated.',
        planSaved: 'Plan saved.',
        planDeleted: 'Plan deleted.',
        planFailed: 'Could not save that plan.',
        invoiceSaved: 'Invoice updated.',
        invoiceFailed: 'Could not update that invoice.',
        enquirySent: 'Thanks — our team will be in touch.',
        enquirySaved: 'Enquiry updated.',
        enquiryFailed: 'Could not send that enquiry.',
        enquiryActionSaved: 'Action recorded.',
    },

    usersAdmin: {
        title: 'Users',
        colName: 'Name',
        colEmail: 'Email',
        colAccess: 'Access',
        colJoined: 'Joined',
        colStatus: 'Status',
        filterSearch: 'Search',
        searchPlaceholder: 'Name or email…',
        filterRole: 'Role',
        filterStatus: 'Status',
        allRoles: 'All roles',
        allStatuses: 'All statuses',
        active: 'Active',
        inactive: 'Inactive',
        activate: 'Activate',
        deactivate: 'Deactivate',
        addUser: 'Add user',
        manageAccess: 'Manage access',
        verifiedBadge: 'Verified',
        activity: 'Activity',
        loginAs: 'Sign in as',
        loginAsConfirm: (who: string) =>
            `You will be signed in as ${who}. The way back is a normal sign-out and sign-in.`,
        loginAsCta: 'Sign in as this user',
        userCreated: 'User created.',
        saved: 'Saved.',
        saveFailed: 'Could not save.',

        createHint: 'The account is claimed when the person first signs in with this email.',
        createEmailLabel: 'Email',
        createEmailPlaceholder: 'person@example.com',
        createNameLabel: 'Name (optional)',
        createRoleLabel: 'Role',
        createSubmit: 'Create user',
    },

    accessAdmin: {
        tab: 'Access & limits',
        limitsHint: 'Quotas: 0 means unlimited. Any other number caps how many a member of this role may own.',

        groups: {
            project: 'Projects',
            task: 'Tasks',
            moderation: 'Moderation',
            audit: 'Audit',
            admin: 'Administration',
            billing: 'Plans & subscriptions',
            invoice: 'Invoices',
            enquiry: 'Sales enquiries',
            email: 'Email',
            file: 'Files',
            signing: 'Token signing',
        } as Record<string, string>,
        rolesTitle: 'Roles',
        bindingsTitle: 'Slots',
        newRole: 'New role',
        bindingsHint: 'Bind each behavioural slot to a role. Sign-up always uses the default slot.',
        unbound: '— none —',
        save: 'Save',
        saved: 'Saved.',
        saveFailed: 'Could not save.',
        roleDeleted: 'Role deleted.',
        reassignPrompt: (name: string) => `This role is still in use. Move those accounts to “${name}” and delete it?`,
        delete: 'Delete role',
        pickRole: 'Pick a role to edit.',
    },

    manageAccess: {
        title: 'Manage access',
        confirmWord: 'OWNER',
        roleLabel: 'Role',
        membersLabel: 'Members',
        variablesTitle: 'Template fields',
        variablesHint: 'Fill the placeholders this template uses.',
        verifiedLabel: 'Verified badge',
        showOverrides: 'Per-account overrides',
        hideOverrides: 'Hide overrides',
        overridesHint: 'Grant or revoke individual permissions and caps for this one account, on top of its role.',
        limitsTitle: 'Limits',
        usage: (used: number, limit: number | null) => `${used}/${limit === null ? '∞' : limit} used`,
        unlimited: 'Unlimited',
        inheritPlaceholder: 'Inherit',
        inherit: 'Reset to inherited',
        permissionsTitle: 'Permissions',
        lastOwner: 'This is the last owner and cannot be demoted or deactivated.',
        clientsWarning: (n: number) => `This account is still linked to ${n} record(s); changing its role leaves them behind.`,
        ownerWarning: 'You are promoting this account to OWNER — full control of the platform. Type OWNER to confirm.',
        confirmPrompt: (word: string) => `Type ${word} to confirm`,
        save: 'Save',
    },

    filters: {
        button: 'Filters',
        buttonWithCount: (n: number) => `Filters (${n})`,
        title: 'Filters',
        apply: 'Apply',
        clear: 'Clear',
    },

    upgrade: {
        cta: 'Upgrade',
        modalTitle: 'Upgrade',
        stamp: 'Upgrade',

        priceAmount: 9,
        howToGet: 'Contact the platform owner to upgrade your account.',
        features: {
            export: {
                title: 'Export projects',
                blurb: 'Download any project and its tasks as JSON.',
                benefits: ['Full project export', 'Machine-readable JSON', 'Back up or migrate your data'],
            },
            unlimitedProjects: {
                title: 'More projects',
                blurb: 'Create as many projects as you need.',
                benefits: ['No project cap', 'Room to organize everything'],
            },
        } as Record<string, { title: string; blurb: string; benefits: string[] }>,
    },

    limits: {
        reachedHint: 'You have reached your limit for this resource.',
    },

    platformSettings: {
        title: 'Platform settings',
        signupsOpenLabel: 'Sign-ups open',
        signupsOpenHint: 'When off, new accounts cannot be created (existing accounts still sign in).',
        salesContactLabel: 'Sales contact',
        salesContactHint: 'Email address or URL shown to accounts that need to contact sales for a manual plan.',
        announcementLabel: 'Announcement',
        announcementHint: 'A short message shown in the app shell. Leave empty to show nothing.',
        save: 'Save',
        saved: 'Settings saved.',
        saveFailed: 'Could not save settings.',
    },

    admin: {
        tabOverview: 'Overview',
        tabUsers: 'Users',
        tabSettings: 'Settings',
    },

    overview: {
        title: 'Overview',
        signupsTotal: 'Total sign-ups',
        wau: 'Weekly active',
        retention: 'D30 retention',
        projectsTotal: 'Projects',
        tasksTotal: 'Tasks',
        reportQueue: 'Open reports',
        na: 'n/a',
        last30Period: 'vs. 30 days ago',
        signupsChart: 'Sign-ups per week',
        signupsChartSubtitle: 'Last 12 weeks',
        signupsSeries: 'Sign-ups',
        tasksChart: 'Tasks by status',
        projectsChart: 'Projects by visibility',
        rolesChart: 'Accounts by role',
        noData: 'Nothing to chart yet.',
    },

    moderation: {
        title: 'Moderation',
        reportsTitle: 'Open reports',
        auditTitle: 'Audit log',
        reportsEmpty: 'No open reports.',
        auditWhen: 'When',
        auditActor: 'Account',
        auditAction: 'Action',
        auditTarget: 'Target',
        auditDetail: 'Detail',
        auditAll: 'All',
        auditSearchPlaceholder: 'Account, action, target or detail',
        auditFrom: 'From',
        auditTo: 'To',
        auditFilteredByActor: 'Showing activity for one account only.',
        auditEmpty: 'No audit entries yet.',
        resolve: 'Resolve',
        resolved: 'Report resolved.',
        resolvePrompt: 'Resolution note (optional):',
        colTarget: 'Target',
        colReason: 'Reason',
        colReporter: 'Reporter',
        colWhen: 'When',
        colActor: 'Actor',
        colAction: 'Action',
        colDetail: 'Detail',

        reportTitle: 'Report',
        reportCategoriesLabel: 'What kind of problem?',
        reportCategories: [
            { key: 'spam', label: 'Spam' },
            { key: 'abuse', label: 'Abusive' },
            { key: 'inappropriate', label: 'Inappropriate' },
            { key: 'other', label: 'Other' },
        ],
        reportReasonLabel: 'Why are you reporting this?',
        reportReasonPlaceholder: 'Describe the problem…',
        reportSubmit: 'Submit report',
        reportSent: 'Report submitted.',
        reportFailed: 'Could not submit the report.',
    },

    projects: {
        title: 'Projects',
        empty: 'No projects yet. Create your first one.',
        newProject: 'New project',
        nameLabel: 'Name',
        namePlaceholder: 'Project name',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'What is this project about?',
        visibilityLabel: 'Visibility',
        visibilityPrivate: 'Private',
        visibilityShared: 'Shared',
        create: 'Create project',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        deleteConfirm: (name: string) => `Delete "${name}" and all its tasks?`,
        export: 'Export',
        open: 'Open',
        sharedBadge: 'Shared',
        privateBadge: 'Private',
        noDescription: 'No description.',
        tasksTitle: 'Tasks',
        addTask: 'Add task',
        titleLabel: 'Title',
        taskPlaceholder: 'Task title',
        taskCount: (n: number) => `${n} task${n === 1 ? '' : 's'}`,
        statusLabel: 'Column',
        statusPlanned: 'Planned',
        statusInProgress: 'In progress',
        statusShipped: 'Shipped',
        taskSelected: (title: string) => `Selected: ${title}`,
        noTaskSelected: 'Pick a task to move or delete it.',
        deleteTask: 'Delete task',
        moveBack: 'Move back',
        moveForward: 'Move forward',
        deleteTaskConfirm: (title: string) => `Delete "${title}"?`,
        created: 'Project created.',
        saved: 'Project saved.',
        deleted: 'Project deleted.',
        saveFailed: 'Could not save the project.',
        exportFailed: 'Could not export the project.',

        updatedAt: (date: string) => `Updated ${date}`,
        statTasksTitle: 'Tasks tracked',
        statTasksDesc: 'Total in this project',
        statAgeTitle: 'Project age',
        statAgeDesc: 'Days since created',
        statVisibilityTitle: 'Visibility',
        statVisibilitySharedDesc: 'Visible to the team',
        statVisibilityPrivateDesc: 'Visible only to you',

        tabRoadmap: 'Roadmap',
        tabSettings: 'Settings',
        dangerZone: 'Danger zone',
        deleteProjectHint: 'Deleting a project removes all of its tasks. This cannot be undone.',

        iconLabel: 'Icon',
        colorLabel: 'Color',
        priorityLabel: 'Priority',
        priorityHint: 'How urgent this project is, 1–5. Used only for your own ordering.',
        dueDateLabel: 'Due date',
        notifyLabel: 'Notify me on activity',
        notifyHelp: 'Get an in-app notification when a task in this project changes.',
    },

    modal: {
        cancel: 'Cancel',
        save: 'Save',
        apiKeyTitle: 'New API key',
        webhookTitle: 'Webhook endpoint',
        fileSourceTitle: 'Storage source',
        createUserTitle: 'Add user',
        deleteAccountTitle: 'Delete account',
        deleteAccountBody: 'This permanently removes your account and everything you own.',
        deleteAccountHint: (word: string) => `Type ${word} to confirm.`,
        confirmDeleteAccount: 'Delete my account',
        createProjectTitle: 'New project',
        createTaskTitle: 'New task',
        deleteTaskTitle: 'Delete task',
        deleteProjectTitle: 'Delete project',
        reportTitle: 'Report',
        resolveReportTitle: 'Resolve report',
        contactSalesTitle: 'Contact sales',
        planEditorTitle: 'Plan',
        upgradeTitle: 'Upgrade',
        manageAccessTitle: 'Manage access',
        impersonateTitle: 'Sign in as user',
        filtersTitle: 'Filters',
        signingPublicKeyTitle: 'Public key',
        rotateSigningKeyTitle: 'Rotate signing key',
    },
} as const

export type AppStrings = typeof STRINGS
