#!/bin/sh
# Enumerates every route declared in api/src/routers and probes a table of
# authorization expectations against a running local stack. Writes the matrix to
# docs/authorization-matrix.md, echoes it on stdout, and exits non-zero when any
# probe disagrees with its expectation.
#
#   npm run dev:api
#   sh scripts/authz-sweep.sh
set -eu

API="${API_URL:-http://localhost:6000}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JARS="$(mktemp -d)"
FAILURES=0

cleanup() { rm -rf "$JARS"; }
trap cleanup EXIT

# The matrix is committed documentation; stdout is kept so the run is still
# readable while it happens.
MATRIX_OUT="${MATRIX_OUT:-$ROOT/docs/authorization-matrix.md}"
MATRIX="$JARS/matrix.md"
PROBED="$JARS/probed.txt"
: > "$PROBED"
exec 3>&1 >"$MATRIX"

# --- the caller set ------------------------------------------------------
# Dev login mints a session for any address; the first account ever created is
# the owner, so the owner jar is whoever the local database already made one.
sign_in() {
    name="$1"
    email="$2"
    curl -s -o /dev/null -c "$JARS/$name" \
        -X POST "$API/api/auth/dev" \
        -H 'content-type: application/json' \
        -d "{\"email\":\"$email\"}" || true
}

probe_body() {
    caller="$1"
    method="$2"
    path="$3"
    body="$4"
    expected="$5"

    if [ "$caller" = "anon" ]; then
        got=$(curl -s -o /dev/null -w '%{http_code}' -X "$method" "$API$path" \
            -H 'content-type: application/json' -d "$body")
    else
        got=$(curl -s -o /dev/null -w '%{http_code}' -b "$JARS/$caller" -X "$method" "$API$path" \
            -H 'content-type: application/json' -d "$body")
    fi

    if [ "$got" = "$expected" ]; then
        result="ok"
    else
        result="**MISMATCH**"
        FAILURES=$((FAILURES + 1))
    fi
    printf '%s %s\n' "$method" "$path" >> "$PROBED"
    printf '| %s | %s %s | %s | %s | %s |\n' "$caller" "$method" "$path" "$expected" "$got" "$result"
}

probe() {
    caller="$1"
    method="$2"
    path="$3"
    expected="$4"

    if [ "$caller" = "anon" ]; then
        got=$(curl -s -o /dev/null -w '%{http_code}' -X "$method" "$API$path")
    else
        got=$(curl -s -o /dev/null -w '%{http_code}' -b "$JARS/$caller" -X "$method" "$API$path")
    fi

    if [ "$got" = "$expected" ]; then
        result="ok"
    else
        result="**MISMATCH**"
        FAILURES=$((FAILURES + 1))
    fi
    printf '%s %s\n' "$method" "$path" >> "$PROBED"
    printf '| %s | %s %s | %s | %s | %s |\n' "$caller" "$method" "$path" "$expected" "$got" "$result"
}

# --- the route inventory -------------------------------------------------
inventory() {
    # slurp whole files, because a route's generic parameters routinely put the
    # path on the next line: app.get<{ Params: … }>(\n    '/api/thing',
    perl -0777 -ne 'while (/app\.(get|post|put|patch|delete)\s*(?:<.*?>)?\s*\(\s*\x27([^\x27]+)\x27/gs) { print "$1 $2\n" }' \
        "$ROOT"/api/src/routers/*.ts | sort -u
}

printf '# Authorization matrix\n\n'
printf 'Generated by `scripts/authz-sweep.sh` on %s against commit `%s`.\n\n' \
    "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"

printf '## Route inventory\n\n'
printf 'Every path declared in `api/src/routers`. The list is enumerated from the router\n'
printf 'files, never hand-maintained — a route missing here is a failure of the sweep, not of the route.\n\n'
printf '```\n'
inventory
printf '```\n\n'

sign_in owner "${OWNER_EMAIL:-owner@example.com}"
sign_in member "${MEMBER_EMAIL:-member@example.com}"

printf '## Probes\n\n'
printf '| Caller | Route | Expected | Got | Result |\n'
printf '| --- | --- | --- | --- | --- |\n'

# public surface
probe anon GET /api/health 200
probe anon GET /api/version 200
probe anon GET /api/ready 200

# authentication is required, and it answers 401 not 403
probe anon GET /api/auth/me 401
probe anon GET /api/users 401
probe anon GET /api/moderation/audit-log 401
probe anon GET /api/roles 401
probe anon GET /api/ops/status 401
probe anon GET /api/retention 401
probe anon GET /api/jobs/schedules 401
probe anon GET /api/webhooks 401
probe anon GET /api/asset-sources 401
# a mutating route with no body 400s in the validation phase, which runs ahead of
# the auth preHandler — so the probe sends a valid body to reach the guard
probe_body anon POST /api/tickets '{"subject":"sweep","body":"sweep"}' 401

# a signed-in account without the capability is 403, never 404
probe member GET /api/users 403
probe member GET /api/moderation/audit-log 403
probe member GET /api/roles 403
probe member GET /api/ops/status 403
probe member GET /api/retention 403
probe member GET /api/jobs/schedules 403
probe member GET /api/webhooks 403
probe member GET /api/service-accounts 403
probe member GET /api/realms 403
probe member GET /api/realm-regions 403
probe member GET /api/admin/projects 403
probe member GET /api/admin/waitlist 403
probe member GET /api/role-applications 403

# the owner holds the whole catalog
probe owner GET /api/users 200
probe owner GET /api/moderation/audit-log 200
probe owner GET /api/roles 200
probe owner GET /api/ops/status 200
probe owner GET /api/retention 200
probe owner GET /api/jobs/schedules 200
probe owner GET /api/webhooks 200
probe owner GET /api/realms 200
probe owner GET /api/realm-regions 200
probe owner GET /api/admin/projects 200
probe owner GET /api/role-applications 200

# the game runtime API is public, unauthenticated and not enveloped
probe anon GET /api/public/unknown-project/release/manifest 404

# a realm authenticates with a bearer token, never a cookie — a session is refused
probe anon GET /api/realm/builds/next 401
probe owner GET /api/realm/builds/next 401

# a row the caller may not see is 404, never 403 — existence is not confirmed
probe member GET /api/tickets/00000000-0000-0000-0000-000000000000 404
probe owner GET /api/tickets/00000000-0000-0000-0000-000000000000 404
probe owner GET /api/files/00000000-0000-0000-0000-000000000000 404

# a non-member gets 404 on a project, not 403 — membership is not confirmed either
probe member GET /api/projects/00000000-0000-0000-0000-000000000000 404
probe owner GET /api/projects/00000000-0000-0000-0000-000000000000 404
probe anon GET /api/projects 401

# path traversal on the byte route resolves to an unknown id, byte-identically
probe owner GET '/api/files/..%2f..%2fetc%2fpasswd' 404
probe owner GET '/api/files/../../etc/passwd' 404

printf '\n## Coverage\n\n'
printf 'Routes the inventory found that no probe asserts. The inventory is enumerated from the\n'
printf 'router files; this list is what nobody has stated an expectation for yet.\n\n'

# a probe hits a concrete id where the router declares a parameter, so both
# sides are reduced to their route shape before they are compared
normalise() {
    awk '{
        method = toupper($1)
        n = split($2, seg, "/")
        out = ""
        for (i = 2; i <= n; i++) {
            s = seg[i]
            if (s ~ /^:/ || s ~ /^[0-9]+$/ || s ~ /%/ || s ~ /^[0-9a-fA-F]{8}-/ || length(s) > 24) s = ":param"
            out = out "/" s
        }
        print method, out
    }'
}

inventory | normalise | sort -u > "$JARS/all.txt"
sed "s/'//g" "$PROBED" | normalise | sort -u > "$JARS/hit.txt"
comm -23 "$JARS/all.txt" "$JARS/hit.txt" > "$JARS/unprobed.txt"

TOTAL=$(wc -l < "$JARS/all.txt" | tr -d ' ')
UNPROBED=$(wc -l < "$JARS/unprobed.txt" | tr -d ' ')

printf '%s of %s routes probed, %s unprobed.\n\n' "$((TOTAL - UNPROBED))" "$TOTAL" "$UNPROBED"
if [ "$UNPROBED" -gt 0 ]; then
    printf '```\n'
    cat "$JARS/unprobed.txt"
    printf '```\n'
fi

printf '\n'
if [ "$FAILURES" -eq 0 ]; then
    printf 'All probes matched.\n'
else
    printf '%s probe(s) did NOT match. This is a finding, not a flaky test.\n' "$FAILURES"
fi

exec 1>&3
cat "$MATRIX"

cp "$MATRIX" "$MATRIX_OUT"
printf '\nwritten to %s\n' "$MATRIX_OUT" >&2

exit "$FAILURES"
